// this file is automatically generated, do not edit!
#include "abandoned_camp_common_chest_26_3.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[26] = {"minecraft:arrow", "minecraft:map", "minecraft:bone", "minecraft:cobweb", "minecraft:compass", "minecraft:map", "minecraft:firework_rocket", "minecraft:fishing_rod", "minecraft:flint_and_steel", "minecraft:glass_bottle", "minecraft:lead", "minecraft:leather", "minecraft:bundle", "minecraft:rabbit_hide", "minecraft:saddle", "minecraft:white_candle", "minecraft:bow", "minecraft:bucket", "minecraft:copper_axe", "minecraft:copper_boots", "minecraft:copper_chestplate", "minecraft:copper_leggings", "minecraft:copper_spear", "minecraft:copper_sword", "minecraft:spyglass", "minecraft:shears"};
static int global_item_ids[26] = {ITEM_ARROW, ITEM_MAP, ITEM_BONE, ITEM_COBWEB, ITEM_COMPASS, ITEM_MAP, ITEM_FIREWORK_ROCKET, ITEM_FISHING_ROD, ITEM_FLINT_AND_STEEL, ITEM_GLASS_BOTTLE, ITEM_LEAD, ITEM_LEATHER, ITEM_BUNDLE, ITEM_RABBIT_HIDE, ITEM_SADDLE, ITEM_WHITE_CANDLE, ITEM_BOW, ITEM_BUCKET, ITEM_COPPER_AXE, ITEM_COPPER_BOOTS, ITEM_COPPER_CHESTPLATE, ITEM_COPPER_LEGGINGS, ITEM_COPPER_SPEAR, ITEM_COPPER_SWORD, ITEM_SPYGLASS, ITEM_SHEARS};

static int precomputed_loot__0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static int entry_to_item__0[16] = {0, 1, 2, 3, 4, 1, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static int entry_functions_count__0[16] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static LootFunction loot_functions__0[16];
static const LootPool abandoned_camp_common_chest_26_3__0 = {
    .min_rolls = 4,
    .max_rolls = 6,
    .roll_count_function = roll_count_uniform,
    .entry_count = 16,
    .total_weight = 16,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static int entry_to_item__1[10] = {16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static int entry_functions_count__1[10] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__1[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static LootFunction loot_functions__1[10];
static const LootPool abandoned_camp_common_chest_26_3__1 = {
    .min_rolls = 2,
    .max_rolls = 2,
    .roll_count_function = roll_count_constant,
    .entry_count = 10,
    .total_weight = 10,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {abandoned_camp_common_chest_26_3__0, abandoned_camp_common_chest_26_3__1};
static LootTableContext context = {
    .version = MC_26_3,
    .item_count = 26,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 4, 4);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 4);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 2);
    create_set_count(&(loot_pool__0->loot_functions[6]), 2, 4);
    create_set_count(&(loot_pool__0->loot_functions[7]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[9]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[10]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[11]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[12]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[13]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[14]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[15]), 1, 3);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[3]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[4]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[5]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[6]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[7]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[9]), 1, 1);
}

LootTableContext* init_abandoned_camp_common_chest_26_3() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
