// this file is automatically generated, do not edit!
#ifndef BASTION_HOGLIN_STABLE_1_16_1_H
#define BASTION_HOGLIN_STABLE_1_16_1_H

#include "../loot_table_context.h"

LootTableContext* init_bastion_hoglin_stable_1_16_1();

#endif //BASTION_HOGLIN_STABLE_1_16_1_H
