// this file is automatically generated, do not edit!
#ifndef BASTION_BRIDGE_1_16_1_H
#define BASTION_BRIDGE_1_16_1_H

#include "../loot_table_context.h"

void init_bastion_bridge_1_16_1(LootTableContext* context);

#endif //BASTION_BRIDGE_1_16_1_H
