// this file is automatically generated, do not edit!
#ifndef BASTION_HOGLIN_STABLE_1_16_5_H
#define BASTION_HOGLIN_STABLE_1_16_5_H

#include "../loot_table_context.h"

LootTableContext* init_bastion_hoglin_stable_1_16_5(int version);

#endif //BASTION_HOGLIN_STABLE_1_16_5_H
