// this file is automatically generated, do not edit!
#ifndef BASTION_OTHER_1_21_1_H
#define BASTION_OTHER_1_21_1_H

#include "../loot_table_context.h"

LootTableContext* init_bastion_other_1_21_1();

#endif //BASTION_OTHER_1_21_1_H
