// this file is automatically generated, do not edit!
#ifndef BASTION_BRIDGE_1_20_H
#define BASTION_BRIDGE_1_20_H

#include "../loot_table_context.h"

LootTableContext* init_bastion_bridge_1_20();

#endif //BASTION_BRIDGE_1_20_H
