// this file is automatically generated, do not edit!
#include <pthread.h>

#include "bastion_bridge_1_20.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[21] = {"minecraft:lodestone", "minecraft:crossbow", "minecraft:spectral_arrow", "minecraft:gilded_blackstone", "minecraft:crying_obsidian", "minecraft:gold_block", "minecraft:gold_ingot", "minecraft:iron_ingot", "minecraft:golden_sword", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:golden_axe", "minecraft:string", "minecraft:leather", "minecraft:arrow", "minecraft:iron_nugget", "minecraft:gold_nugget", "minecraft:snout_armor_trim_smithing_template", "minecraft:netherite_upgrade_smithing_template"};
static int global_item_ids[21] = {ITEM_LODESTONE, ITEM_CROSSBOW, ITEM_SPECTRAL_ARROW, ITEM_GILDED_BLACKSTONE, ITEM_CRYING_OBSIDIAN, ITEM_GOLD_BLOCK, ITEM_GOLD_INGOT, ITEM_IRON_INGOT, ITEM_GOLDEN_SWORD, ITEM_GOLDEN_CHESTPLATE, ITEM_GOLDEN_HELMET, ITEM_GOLDEN_LEGGINGS, ITEM_GOLDEN_BOOTS, ITEM_GOLDEN_AXE, ITEM_STRING, ITEM_LEATHER, ITEM_ARROW, ITEM_IRON_NUGGET, ITEM_GOLD_NUGGET, ITEM_SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_NETHERITE_UPGRADE_SMITHING_TEMPLATE};

static int precomputed_loot__0[1] = {0};
static int entry_to_item__0[1] = {0};
static int entry_functions_count__0[1] = {1};
static int entry_functions_index__0[1] = {0};
static LootFunction loot_functions__0[1];
static const LootPool bastion_bridge_1_20__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[13] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static int entry_to_item__1[13] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static int entry_functions_count__1[13] = {2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
static int entry_functions_index__1[13] = {0, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17};
static LootFunction loot_functions__1[19];
static const LootPool bastion_bridge_1_20__1 = {
    .min_rolls = 1,
    .max_rolls = 2,
    .roll_count_function = roll_count_uniform,
    .entry_count = 13,
    .total_weight = 13,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[5] = {0, 1, 2, 3, 4};
static int entry_to_item__2[5] = {14, 15, 16, 17, 18};
static int entry_functions_count__2[5] = {1, 1, 1, 1, 1};
static int entry_functions_index__2[5] = {0, 1, 2, 3, 4};
static LootFunction loot_functions__2[5];
static const LootPool bastion_bridge_1_20__2 = {
    .min_rolls = 2,
    .max_rolls = 4,
    .roll_count_function = roll_count_uniform,
    .entry_count = 5,
    .total_weight = 5,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};
static int precomputed_loot__3[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__3[2] = {-1, 19};
static int entry_functions_count__3[2] = {0, 0};
static int entry_functions_index__3[2] = {0, 0};
static LootFunction loot_functions__3[0];
static const LootPool bastion_bridge_1_20__3 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 12,
    .precomputed_loot = precomputed_loot__3,
    .entry_to_item = entry_to_item__3,
    .entry_functions_count = entry_functions_count__3,
    .entry_functions_index = entry_functions_index__3,
    .loot_functions = loot_functions__3,
};
static int precomputed_loot__4[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__4[2] = {-1, 20};
static int entry_functions_count__4[2] = {0, 0};
static int entry_functions_index__4[2] = {0, 0};
static LootFunction loot_functions__4[0];
static const LootPool bastion_bridge_1_20__4 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 10,
    .precomputed_loot = precomputed_loot__4,
    .entry_to_item = entry_to_item__4,
    .entry_functions_count = entry_functions_count__4,
    .entry_functions_index = entry_functions_index__4,
    .loot_functions = loot_functions__4,
};

static LootPool loot_pools[5] = {bastion_bridge_1_20__0, bastion_bridge_1_20__1, bastion_bridge_1_20__2, bastion_bridge_1_20__3, bastion_bridge_1_20__4};
static LootTableContext context = {
    .version = MC_1_20,
    .item_count = 21,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 5,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 1);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_skip_calls(&(loot_pool__1->loot_functions[0]), 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[1]), MC_1_20, get_item_type("minecraft:crossbow"), 1);
    create_set_count(&(loot_pool__1->loot_functions[2]), 10, 28);
    create_set_count(&(loot_pool__1->loot_functions[3]), 8, 12);
    create_set_count(&(loot_pool__1->loot_functions[4]), 3, 8);
    create_set_count(&(loot_pool__1->loot_functions[5]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[6]), 4, 9);
    create_set_count(&(loot_pool__1->loot_functions[7]), 4, 9);
    create_set_count(&(loot_pool__1->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[9]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[10]), MC_1_20, get_item_type("minecraft:golden_chestplate"), 1);
    create_set_count(&(loot_pool__1->loot_functions[11]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[12]), MC_1_20, get_item_type("minecraft:golden_helmet"), 1);
    create_set_count(&(loot_pool__1->loot_functions[13]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[14]), MC_1_20, get_item_type("minecraft:golden_leggings"), 1);
    create_set_count(&(loot_pool__1->loot_functions[15]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[16]), MC_1_20, get_item_type("minecraft:golden_boots"), 1);
    create_set_count(&(loot_pool__1->loot_functions[17]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[18]), MC_1_20, get_item_type("minecraft:golden_axe"), 1);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 1, 6);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 3);
    create_set_count(&(loot_pool__2->loot_functions[2]), 5, 17);
    create_set_count(&(loot_pool__2->loot_functions[3]), 2, 6);
    create_set_count(&(loot_pool__2->loot_functions[4]), 2, 6);
    LootPool* loot_pool__3 = &(context.loot_pools[3]);
    LootPool* loot_pool__4 = &(context.loot_pools[4]);
}

LootTableContext* init_bastion_bridge_1_20() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
