// this file is automatically generated, do not edit!
#ifndef BASTION_OTHER_1_16_5_H
#define BASTION_OTHER_1_16_5_H

#include "../loot_table_context.h"

void init_bastion_other_1_16_5(LootTableContext* context);

#endif //BASTION_OTHER_1_16_5_H
