// this file is automatically generated, do not edit!
#ifndef BASTION_TREASURE_1_16_1_H
#define BASTION_TREASURE_1_16_1_H

#include "../loot_table_context.h"

LootTableContext* init_bastion_treasure_1_16_1();

#endif //BASTION_TREASURE_1_16_1_H
