// this file is automatically generated, do not edit!
#include "bastion_other_1_16_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[27] = {"minecraft:crossbow", "minecraft:ancient_debris", "minecraft:netherite_scrap", "minecraft:spectral_arrow", "minecraft:piglin_banner_pattern", "minecraft:music_disc_pigstep", "minecraft:book", "minecraft:golden_boots", "minecraft:gold_block", "minecraft:crossbow", "minecraft:gold_ingot", "minecraft:iron_ingot", "minecraft:golden_sword", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:crying_obsidian", "minecraft:gilded_blackstone", "minecraft:chain", "minecraft:magma_cream", "minecraft:bone_block", "minecraft:iron_nugget", "minecraft:obsidian", "minecraft:gold_nugget", "minecraft:string", "minecraft:arrow"};
static int global_item_ids[27] = {ITEM_CROSSBOW, ITEM_ANCIENT_DEBRIS, ITEM_NETHERITE_SCRAP, ITEM_SPECTRAL_ARROW, ITEM_PIGLIN_BANNER_PATTERN, ITEM_MUSIC_DISC_PIGSTEP, ITEM_BOOK, ITEM_GOLDEN_BOOTS, ITEM_GOLD_BLOCK, ITEM_CROSSBOW, ITEM_GOLD_INGOT, ITEM_IRON_INGOT, ITEM_GOLDEN_SWORD, ITEM_GOLDEN_CHESTPLATE, ITEM_GOLDEN_HELMET, ITEM_GOLDEN_LEGGINGS, ITEM_GOLDEN_BOOTS, ITEM_CRYING_OBSIDIAN, ITEM_GILDED_BLACKSTONE, ITEM_CHAIN, ITEM_MAGMA_CREAM, ITEM_BONE_BLOCK, ITEM_IRON_NUGGET, ITEM_OBSIDIAN, ITEM_GOLD_NUGGET, ITEM_STRING, ITEM_ARROW};

static int precomputed_loot__0[100] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7};
static int entry_to_item__0[8] = {0, 1, 2, 3, 4, 5, 6, -1};
static int entry_functions_count__0[8] = {2, 1, 1, 1, 1, 1, 1, 0};
static int entry_functions_index__0[8] = {0, 2, 3, 4, 5, 6, 7, 8};
static LootFunction loot_functions__0[8];
static const LootPool bastion_other_1_16_1__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 8,
    .total_weight = 100,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[12] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10};
static int entry_to_item__1[11] = {7, 8, 0, 10, 11, 12, 13, 14, 15, 7, -1};
static int entry_functions_count__1[11] = {2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0};
static int entry_functions_index__1[11] = {0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static LootFunction loot_functions__1[11];
static const LootPool bastion_other_1_16_1__1 = {
    .min_rolls = 2,
    .max_rolls = 2,
    .roll_count_function = roll_count_constant,
    .entry_count = 11,
    .total_weight = 12,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[11] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9};
static int entry_to_item__2[10] = {17, 18, 19, 20, 21, 22, 23, 24, 25, 26};
static int entry_functions_count__2[10] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__2[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static LootFunction loot_functions__2[10];
static const LootPool bastion_other_1_16_1__2 = {
    .min_rolls = 3,
    .max_rolls = 5,
    .roll_count_function = roll_count_uniform,
    .entry_count = 10,
    .total_weight = 11,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static LootPool loot_pools[3] = {bastion_other_1_16_1__0, bastion_other_1_16_1__1, bastion_other_1_16_1__2};
static LootTableContext context = {
    .version = MC_1_16_1,
    .item_count = 27,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_skip_calls(&(loot_pool__0->loot_functions[0]), 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[1]), MC_1_16_1, get_item_type("minecraft:crossbow"), 1);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[4]), 2, 15);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[6]), 1, 1);
    create_enchant_randomly_one_enchant(&(loot_pool__0->loot_functions[7]), get_enchantment_from_name("minecraft:soul_speed"));
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 1);
    create_enchant_randomly_one_enchant(&(loot_pool__1->loot_functions[1]), get_enchantment_from_name("minecraft:soul_speed"));
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[3]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[4]), 1, 6);
    create_set_count(&(loot_pool__1->loot_functions[5]), 1, 6);
    create_set_count(&(loot_pool__1->loot_functions[6]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[7]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[9]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[10]), 1, 1);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 1, 5);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__2->loot_functions[2]), 2, 10);
    create_set_count(&(loot_pool__2->loot_functions[3]), 2, 6);
    create_set_count(&(loot_pool__2->loot_functions[4]), 3, 6);
    create_set_count(&(loot_pool__2->loot_functions[5]), 2, 8);
    create_set_count(&(loot_pool__2->loot_functions[6]), 4, 6);
    create_set_count(&(loot_pool__2->loot_functions[7]), 2, 8);
    create_set_count(&(loot_pool__2->loot_functions[8]), 4, 6);
    create_set_count(&(loot_pool__2->loot_functions[9]), 5, 17);
}

LootTableContext* init_bastion_other_1_16_1() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
