// this file is automatically generated, do not edit!
#include "bastion_bridge_1_16_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_bastion_bridge_1_16_1(LootTableContext* context) {
    static char* item_names[18] = {"minecraft:lodestone", "minecraft:crossbow", "minecraft:spectral_arrow", "minecraft:gilded_blackstone", "minecraft:crying_obsidian", "minecraft:gold_block", "minecraft:gold_ingot", "minecraft:iron_ingot", "minecraft:golden_sword", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:string", "minecraft:leather", "minecraft:arrow", "minecraft:iron_nugget", "minecraft:gold_nugget"};
    static int global_item_ids[18] = {ITEM_LODESTONE, ITEM_CROSSBOW, ITEM_SPECTRAL_ARROW, ITEM_GILDED_BLACKSTONE, ITEM_CRYING_OBSIDIAN, ITEM_GOLD_BLOCK, ITEM_GOLD_INGOT, ITEM_IRON_INGOT, ITEM_GOLDEN_SWORD, ITEM_GOLDEN_CHESTPLATE, ITEM_GOLDEN_HELMET, ITEM_GOLDEN_LEGGINGS, ITEM_GOLDEN_BOOTS, ITEM_STRING, ITEM_LEATHER, ITEM_ARROW, ITEM_IRON_NUGGET, ITEM_GOLD_NUGGET};
    static int precomputed_loot__0[1] = {0};
    static int entry_to_item__0[1] = {0};
    static int entry_functions_count__0[1] = {1};
    static int entry_functions_index__0[1] = {0};
    static LootPool bastion_bridge_1_16_1__0 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 1,
        .total_weight = 1,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__1[12] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    static int entry_to_item__1[12] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
    static int entry_functions_count__1[12] = {2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2};
    static int entry_functions_index__1[12] = {0, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15};
    static LootPool bastion_bridge_1_16_1__1 = {
        .min_rolls = 1,
        .max_rolls = 2,
        .roll_count_function = roll_count_uniform,
        .entry_count = 12,
        .total_weight = 12,
        .precomputed_loot = precomputed_loot__1,
        .entry_to_item = entry_to_item__1,
        .entry_functions_count = entry_functions_count__1,
        .entry_functions_index = entry_functions_index__1,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__2[5] = {0, 1, 2, 3, 4};
    static int entry_to_item__2[5] = {13, 14, 15, 16, 17};
    static int entry_functions_count__2[5] = {1, 1, 1, 1, 1};
    static int entry_functions_index__2[5] = {0, 1, 2, 3, 4};
    static LootPool bastion_bridge_1_16_1__2 = {
        .min_rolls = 2,
        .max_rolls = 4,
        .roll_count_function = roll_count_uniform,
        .entry_count = 5,
        .total_weight = 5,
        .precomputed_loot = precomputed_loot__2,
        .entry_to_item = entry_to_item__2,
        .entry_functions_count = entry_functions_count__2,
        .entry_functions_index = entry_functions_index__2,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_16_1;
    context->item_count = 18;
    context->item_names = item_names;
    context->global_item_ids = global_item_ids;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 3;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = bastion_bridge_1_16_1__0;
    context->loot_pools[1] = bastion_bridge_1_16_1__1;
    context->loot_pools[2] = bastion_bridge_1_16_1__2;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(1 * sizeof(LootFunction));
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 1);
    LootPool* loot_pool__1 = &(context->loot_pools[1]);
    loot_pool__1->loot_functions = malloc(17 * sizeof(LootFunction));
    create_skip_calls(&(loot_pool__1->loot_functions[0]), 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[1]), MC_1_16_1, get_item_type("minecraft:crossbow"), 1);
    create_set_count(&(loot_pool__1->loot_functions[2]), 2, 12);
    create_set_count(&(loot_pool__1->loot_functions[3]), 5, 8);
    create_set_count(&(loot_pool__1->loot_functions[4]), 3, 8);
    create_set_count(&(loot_pool__1->loot_functions[5]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[6]), 2, 8);
    create_set_count(&(loot_pool__1->loot_functions[7]), 2, 8);
    create_set_count(&(loot_pool__1->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[9]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[10]), MC_1_16_1, get_item_type("minecraft:golden_chestplate"), 1);
    create_set_count(&(loot_pool__1->loot_functions[11]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[12]), MC_1_16_1, get_item_type("minecraft:golden_helmet"), 1);
    create_set_count(&(loot_pool__1->loot_functions[13]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[14]), MC_1_16_1, get_item_type("minecraft:golden_leggings"), 1);
    create_set_count(&(loot_pool__1->loot_functions[15]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[16]), MC_1_16_1, get_item_type("minecraft:golden_boots"), 1);
    LootPool* loot_pool__2 = &(context->loot_pools[2]);
    loot_pool__2->loot_functions = malloc(5 * sizeof(LootFunction));
    create_set_count(&(loot_pool__2->loot_functions[0]), 1, 6);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 3);
    create_set_count(&(loot_pool__2->loot_functions[2]), 5, 17);
    create_set_count(&(loot_pool__2->loot_functions[3]), 2, 6);
    create_set_count(&(loot_pool__2->loot_functions[4]), 2, 6);
}
