// this file is automatically generated, do not edit!
#include <pthread.h>

#include "bastion_other_1_21_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[37] = {"minecraft:diamond_pickaxe", "minecraft:diamond_shovel", "minecraft:crossbow", "minecraft:ancient_debris", "minecraft:netherite_scrap", "minecraft:spectral_arrow", "minecraft:piglin_banner_pattern", "minecraft:music_disc_pigstep", "minecraft:golden_carrot", "minecraft:golden_apple", "minecraft:book", "minecraft:iron_sword", "minecraft:iron_block", "minecraft:golden_boots", "minecraft:golden_axe", "minecraft:gold_block", "minecraft:crossbow", "minecraft:gold_ingot", "minecraft:iron_ingot", "minecraft:golden_sword", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:crying_obsidian", "minecraft:gilded_blackstone", "minecraft:chain", "minecraft:magma_cream", "minecraft:bone_block", "minecraft:iron_nugget", "minecraft:obsidian", "minecraft:gold_nugget", "minecraft:string", "minecraft:arrow", "minecraft:cooked_porkchop", "minecraft:snout_armor_trim_smithing_template", "minecraft:netherite_upgrade_smithing_template"};
static int global_item_ids[37] = {ITEM_DIAMOND_PICKAXE, ITEM_DIAMOND_SHOVEL, ITEM_CROSSBOW, ITEM_ANCIENT_DEBRIS, ITEM_NETHERITE_SCRAP, ITEM_SPECTRAL_ARROW, ITEM_PIGLIN_BANNER_PATTERN, ITEM_MUSIC_DISC_PIGSTEP, ITEM_GOLDEN_CARROT, ITEM_GOLDEN_APPLE, ITEM_BOOK, ITEM_IRON_SWORD, ITEM_IRON_BLOCK, ITEM_GOLDEN_BOOTS, ITEM_GOLDEN_AXE, ITEM_GOLD_BLOCK, ITEM_CROSSBOW, ITEM_GOLD_INGOT, ITEM_IRON_INGOT, ITEM_GOLDEN_SWORD, ITEM_GOLDEN_CHESTPLATE, ITEM_GOLDEN_HELMET, ITEM_GOLDEN_LEGGINGS, ITEM_GOLDEN_BOOTS, ITEM_CRYING_OBSIDIAN, ITEM_GILDED_BLACKSTONE, ITEM_CHAIN, ITEM_MAGMA_CREAM, ITEM_BONE_BLOCK, ITEM_IRON_NUGGET, ITEM_OBSIDIAN, ITEM_GOLD_NUGGET, ITEM_STRING, ITEM_ARROW, ITEM_COOKED_PORKCHOP, ITEM_SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_NETHERITE_UPGRADE_SMITHING_TEMPLATE};

static int precomputed_loot__0[89] = {0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10};
static int entry_to_item__0[11] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static int entry_functions_count__0[11] = {2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__0[11] = {0, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12};
static LootFunction loot_functions__0[13];
static const LootPool bastion_other_1_21_1__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 11,
    .total_weight = 89,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[20] = {0, 0, 1, 1, 2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 9, 10, 11, 12, 13, 13};
static int entry_to_item__1[14] = {11, 12, 13, 14, 15, 2, 17, 18, 19, 20, 21, 22, 13, 24};
static int entry_functions_count__1[14] = {3, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__1[14] = {0, 3, 4, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static LootFunction loot_functions__1[18];
static const LootPool bastion_other_1_21_1__1 = {
    .min_rolls = 2,
    .max_rolls = 2,
    .roll_count_function = roll_count_constant,
    .entry_count = 14,
    .total_weight = 20,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[13] = {0, 0, 1, 2, 2, 3, 4, 5, 6, 7, 8, 8, 9};
static int entry_to_item__2[10] = {25, 26, 27, 28, 29, 30, 31, 32, 33, 34};
static int entry_functions_count__2[10] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__2[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static LootFunction loot_functions__2[10];
static const LootPool bastion_other_1_21_1__2 = {
    .min_rolls = 3,
    .max_rolls = 4,
    .roll_count_function = roll_count_uniform,
    .entry_count = 10,
    .total_weight = 13,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};
static int precomputed_loot__3[12] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__3[2] = {-1, 35};
static int entry_functions_count__3[2] = {0, 0};
static int entry_functions_index__3[2] = {0, 0};
static LootFunction loot_functions__3[0];
static const LootPool bastion_other_1_21_1__3 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 12,
    .precomputed_loot = precomputed_loot__3,
    .entry_to_item = entry_to_item__3,
    .entry_functions_count = entry_functions_count__3,
    .entry_functions_index = entry_functions_index__3,
    .loot_functions = loot_functions__3,
};
static int precomputed_loot__4[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__4[2] = {-1, 36};
static int entry_functions_count__4[2] = {0, 0};
static int entry_functions_index__4[2] = {0, 0};
static LootFunction loot_functions__4[0];
static const LootPool bastion_other_1_21_1__4 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 10,
    .precomputed_loot = precomputed_loot__4,
    .entry_to_item = entry_to_item__4,
    .entry_functions_count = entry_functions_count__4,
    .entry_functions_index = entry_functions_index__4,
    .loot_functions = loot_functions__4,
};

static LootPool loot_pools[5] = {bastion_other_1_21_1__0, bastion_other_1_21_1__1, bastion_other_1_21_1__2, bastion_other_1_21_1__3, bastion_other_1_21_1__4};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 37,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 5,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[1]), MC_1_21_1, get_item_type("minecraft:diamond_pickaxe"), 1);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 1);
    create_skip_calls(&(loot_pool__0->loot_functions[3]), 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[4]), MC_1_21_1, get_item_type("minecraft:crossbow"), 1);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[6]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[7]), 10, 22);
    create_set_count(&(loot_pool__0->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[9]), 1, 1);
    create_set_count(&(loot_pool__0->loot_functions[10]), 6, 17);
    create_set_count(&(loot_pool__0->loot_functions[11]), 1, 1);
    create_enchant_randomly_one_enchant(&(loot_pool__0->loot_functions[12]), get_enchantment_from_name("minecraft:soul_speed"));
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_skip_calls(&(loot_pool__1->loot_functions[0]), 1);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[2]), MC_1_21_1, get_item_type("minecraft:iron_sword"), 1);
    create_set_count(&(loot_pool__1->loot_functions[3]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[4]), 1, 1);
    create_enchant_randomly_one_enchant(&(loot_pool__1->loot_functions[5]), get_enchantment_from_name("minecraft:soul_speed"));
    create_set_count(&(loot_pool__1->loot_functions[6]), 1, 1);
    create_enchant_randomly(&(loot_pool__1->loot_functions[7]), MC_1_21_1, get_item_type("minecraft:golden_axe"), 1);
    create_set_count(&(loot_pool__1->loot_functions[8]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[9]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[10]), 1, 6);
    create_set_count(&(loot_pool__1->loot_functions[11]), 1, 6);
    create_set_count(&(loot_pool__1->loot_functions[12]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[13]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[14]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[15]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[16]), 1, 1);
    create_set_count(&(loot_pool__1->loot_functions[17]), 1, 5);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 1, 5);
    create_set_count(&(loot_pool__2->loot_functions[1]), 2, 10);
    create_set_count(&(loot_pool__2->loot_functions[2]), 2, 6);
    create_set_count(&(loot_pool__2->loot_functions[3]), 3, 6);
    create_set_count(&(loot_pool__2->loot_functions[4]), 2, 8);
    create_set_count(&(loot_pool__2->loot_functions[5]), 4, 6);
    create_set_count(&(loot_pool__2->loot_functions[6]), 2, 8);
    create_set_count(&(loot_pool__2->loot_functions[7]), 4, 6);
    create_set_count(&(loot_pool__2->loot_functions[8]), 5, 17);
    create_set_count(&(loot_pool__2->loot_functions[9]), 1, 1);
    LootPool* loot_pool__3 = &(context.loot_pools[3]);
    LootPool* loot_pool__4 = &(context.loot_pools[4]);
}

LootTableContext* init_bastion_other_1_21_1() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
