// this file is automatically generated, do not edit!
#ifndef BURIED_TREASURE_1_18_H
#define BURIED_TREASURE_1_18_H

#include "../loot_table_context.h"

LootTableContext* init_buried_treasure_1_18();

#endif //BURIED_TREASURE_1_18_H
