// this file is automatically generated, do not edit!
#include "buried_treasure_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_buried_treasure_1_21_11(LootTableContext* context) {
    static char* item_names[17] = {"minecraft:heart_of_the_sea", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:tnt", "minecraft:emerald", "minecraft:diamond", "minecraft:prismarine_crystals", "minecraft:leather_chestplate", "minecraft:iron_sword", "minecraft:iron_spear", "minecraft:cooked_cod", "minecraft:cooked_salmon", "minecraft:potion", "minecraft:copper_nautilus_armor", "minecraft:iron_nautilus_armor", "minecraft:golden_nautilus_armor", "minecraft:diamond_nautilus_armor"};
    static int global_item_ids[17] = {ITEM_HEART_OF_THE_SEA, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_TNT, ITEM_EMERALD, ITEM_DIAMOND, ITEM_PRISMARINE_CRYSTALS, ITEM_LEATHER_CHESTPLATE, ITEM_IRON_SWORD, ITEM_IRON_SPEAR, ITEM_COOKED_COD, ITEM_COOKED_SALMON, ITEM_POTION, ITEM_COPPER_NAUTILUS_ARMOR, ITEM_IRON_NAUTILUS_ARMOR, ITEM_GOLDEN_NAUTILUS_ARMOR, ITEM_DIAMOND_NAUTILUS_ARMOR};
    static int precomputed_loot__0[1] = {0};
    static int entry_to_item__0[1] = {0};
    static int entry_functions_count__0[1] = {0};
    static int entry_functions_index__0[1] = {0};
    static LootPool buried_treasure_1_21_11__0 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 1,
        .total_weight = 1,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__1[35] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
    static int entry_to_item__1[3] = {1, 2, 3};
    static int entry_functions_count__1[3] = {1, 1, 1};
    static int entry_functions_index__1[3] = {0, 1, 2};
    static LootPool buried_treasure_1_21_11__1 = {
        .min_rolls = 5,
        .max_rolls = 8,
        .roll_count_function = roll_count_uniform,
        .entry_count = 3,
        .total_weight = 35,
        .precomputed_loot = precomputed_loot__1,
        .entry_to_item = entry_to_item__1,
        .entry_functions_count = entry_functions_count__1,
        .entry_functions_index = entry_functions_index__1,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__2[15] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
    static int entry_to_item__2[3] = {4, 5, 6};
    static int entry_functions_count__2[3] = {1, 1, 1};
    static int entry_functions_index__2[3] = {0, 1, 2};
    static LootPool buried_treasure_1_21_11__2 = {
        .min_rolls = 1,
        .max_rolls = 3,
        .roll_count_function = roll_count_uniform,
        .entry_count = 3,
        .total_weight = 15,
        .precomputed_loot = precomputed_loot__2,
        .entry_to_item = entry_to_item__2,
        .entry_functions_count = entry_functions_count__2,
        .entry_functions_index = entry_functions_index__2,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__3[3] = {0, 1, 2};
    static int entry_to_item__3[3] = {7, 8, 9};
    static int entry_functions_count__3[3] = {0, 0, 0};
    static int entry_functions_index__3[3] = {0, 0, 0};
    static LootPool buried_treasure_1_21_11__3 = {
        .min_rolls = 0,
        .max_rolls = 1,
        .roll_count_function = roll_count_uniform,
        .entry_count = 3,
        .total_weight = 3,
        .precomputed_loot = precomputed_loot__3,
        .entry_to_item = entry_to_item__3,
        .entry_functions_count = entry_functions_count__3,
        .entry_functions_index = entry_functions_index__3,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__4[2] = {0, 1};
    static int entry_to_item__4[2] = {10, 11};
    static int entry_functions_count__4[2] = {1, 1};
    static int entry_functions_index__4[2] = {0, 1};
    static LootPool buried_treasure_1_21_11__4 = {
        .min_rolls = 2,
        .max_rolls = 2,
        .roll_count_function = roll_count_constant,
        .entry_count = 2,
        .total_weight = 2,
        .precomputed_loot = precomputed_loot__4,
        .entry_to_item = entry_to_item__4,
        .entry_functions_count = entry_functions_count__4,
        .entry_functions_index = entry_functions_index__4,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__5[1] = {0};
    static int entry_to_item__5[1] = {12};
    static int entry_functions_count__5[1] = {0};
    static int entry_functions_index__5[1] = {0};
    static LootPool buried_treasure_1_21_11__5 = {
        .min_rolls = 0,
        .max_rolls = 2,
        .roll_count_function = roll_count_uniform,
        .entry_count = 1,
        .total_weight = 1,
        .precomputed_loot = precomputed_loot__5,
        .entry_to_item = entry_to_item__5,
        .entry_functions_count = entry_functions_count__5,
        .entry_functions_index = entry_functions_index__5,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__6[185] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4};
    static int entry_to_item__6[5] = {-1, 13, 14, 15, 16};
    static int entry_functions_count__6[5] = {0, 1, 1, 1, 1};
    static int entry_functions_index__6[5] = {0, 0, 1, 2, 3};
    static LootPool buried_treasure_1_21_11__6 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 5,
        .total_weight = 185,
        .precomputed_loot = precomputed_loot__6,
        .entry_to_item = entry_to_item__6,
        .entry_functions_count = entry_functions_count__6,
        .entry_functions_index = entry_functions_index__6,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_21_11;
    context->item_count = 17;
    context->item_names = item_names;
    context->global_item_ids = global_item_ids;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 7;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = buried_treasure_1_21_11__0;
    context->loot_pools[1] = buried_treasure_1_21_11__1;
    context->loot_pools[2] = buried_treasure_1_21_11__2;
    context->loot_pools[3] = buried_treasure_1_21_11__3;
    context->loot_pools[4] = buried_treasure_1_21_11__4;
    context->loot_pools[5] = buried_treasure_1_21_11__5;
    context->loot_pools[6] = buried_treasure_1_21_11__6;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(0 * sizeof(LootFunction));
    LootPool* loot_pool__1 = &(context->loot_pools[1]);
    loot_pool__1->loot_functions = malloc(3 * sizeof(LootFunction));
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 4);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 4);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 2);
    LootPool* loot_pool__2 = &(context->loot_pools[2]);
    loot_pool__2->loot_functions = malloc(3 * sizeof(LootFunction));
    create_set_count(&(loot_pool__2->loot_functions[0]), 4, 8);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 2);
    create_set_count(&(loot_pool__2->loot_functions[2]), 1, 5);
    LootPool* loot_pool__3 = &(context->loot_pools[3]);
    loot_pool__3->loot_functions = malloc(0 * sizeof(LootFunction));
    LootPool* loot_pool__4 = &(context->loot_pools[4]);
    loot_pool__4->loot_functions = malloc(2 * sizeof(LootFunction));
    create_set_count(&(loot_pool__4->loot_functions[0]), 2, 4);
    create_set_count(&(loot_pool__4->loot_functions[1]), 2, 4);
    LootPool* loot_pool__5 = &(context->loot_pools[5]);
    loot_pool__5->loot_functions = malloc(0 * sizeof(LootFunction));
    LootPool* loot_pool__6 = &(context->loot_pools[6]);
    loot_pool__6->loot_functions = malloc(4 * sizeof(LootFunction));
    create_set_count(&(loot_pool__6->loot_functions[0]), 1, 1);
    create_set_count(&(loot_pool__6->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__6->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__6->loot_functions[3]), 1, 1);
}
