// this file is automatically generated, do not edit!
#include <pthread.h>

#include "buried_treasure_1_18.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[12] = {"minecraft:heart_of_the_sea", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:tnt", "minecraft:emerald", "minecraft:diamond", "minecraft:prismarine_crystals", "minecraft:leather_chestplate", "minecraft:iron_sword", "minecraft:cooked_cod", "minecraft:cooked_salmon", "minecraft:potion"};
static int global_item_ids[12] = {ITEM_HEART_OF_THE_SEA, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_TNT, ITEM_EMERALD, ITEM_DIAMOND, ITEM_PRISMARINE_CRYSTALS, ITEM_LEATHER_CHESTPLATE, ITEM_IRON_SWORD, ITEM_COOKED_COD, ITEM_COOKED_SALMON, ITEM_POTION};

static int precomputed_loot__0[1] = {0};
static int entry_to_item__0[1] = {0};
static int entry_functions_count__0[1] = {0};
static int entry_functions_index__0[1] = {0};
static LootFunction loot_functions__0[0];
static const LootPool buried_treasure_1_18__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[35] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
static int entry_to_item__1[3] = {1, 2, 3};
static int entry_functions_count__1[3] = {1, 1, 1};
static int entry_functions_index__1[3] = {0, 1, 2};
static LootFunction loot_functions__1[3];
static const LootPool buried_treasure_1_18__1 = {
    .min_rolls = 5,
    .max_rolls = 8,
    .roll_count_function = roll_count_uniform,
    .entry_count = 3,
    .total_weight = 35,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[15] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
static int entry_to_item__2[3] = {4, 5, 6};
static int entry_functions_count__2[3] = {1, 1, 1};
static int entry_functions_index__2[3] = {0, 1, 2};
static LootFunction loot_functions__2[3];
static const LootPool buried_treasure_1_18__2 = {
    .min_rolls = 1,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 3,
    .total_weight = 15,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};
static int precomputed_loot__3[2] = {0, 1};
static int entry_to_item__3[2] = {7, 8};
static int entry_functions_count__3[2] = {0, 0};
static int entry_functions_index__3[2] = {0, 0};
static LootFunction loot_functions__3[0];
static const LootPool buried_treasure_1_18__3 = {
    .min_rolls = 0,
    .max_rolls = 1,
    .roll_count_function = roll_count_uniform,
    .entry_count = 2,
    .total_weight = 2,
    .precomputed_loot = precomputed_loot__3,
    .entry_to_item = entry_to_item__3,
    .entry_functions_count = entry_functions_count__3,
    .entry_functions_index = entry_functions_index__3,
    .loot_functions = loot_functions__3,
};
static int precomputed_loot__4[2] = {0, 1};
static int entry_to_item__4[2] = {9, 10};
static int entry_functions_count__4[2] = {1, 1};
static int entry_functions_index__4[2] = {0, 1};
static LootFunction loot_functions__4[2];
static const LootPool buried_treasure_1_18__4 = {
    .min_rolls = 2,
    .max_rolls = 2,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 2,
    .precomputed_loot = precomputed_loot__4,
    .entry_to_item = entry_to_item__4,
    .entry_functions_count = entry_functions_count__4,
    .entry_functions_index = entry_functions_index__4,
    .loot_functions = loot_functions__4,
};
static int precomputed_loot__5[1] = {0};
static int entry_to_item__5[1] = {11};
static int entry_functions_count__5[1] = {0};
static int entry_functions_index__5[1] = {0};
static LootFunction loot_functions__5[0];
static const LootPool buried_treasure_1_18__5 = {
    .min_rolls = 0,
    .max_rolls = 2,
    .roll_count_function = roll_count_uniform,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__5,
    .entry_to_item = entry_to_item__5,
    .entry_functions_count = entry_functions_count__5,
    .entry_functions_index = entry_functions_index__5,
    .loot_functions = loot_functions__5,
};

static LootPool loot_pools[6] = {buried_treasure_1_18__0, buried_treasure_1_18__1, buried_treasure_1_18__2, buried_treasure_1_18__3, buried_treasure_1_18__4, buried_treasure_1_18__5};
static LootTableContext context = {
    .version = MC_1_18,
    .item_count = 12,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 6,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 4);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 4);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 2);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 4, 8);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 2);
    create_set_count(&(loot_pool__2->loot_functions[2]), 1, 5);
    LootPool* loot_pool__3 = &(context.loot_pools[3]);
    LootPool* loot_pool__4 = &(context.loot_pools[4]);
    create_set_count(&(loot_pool__4->loot_functions[0]), 2, 4);
    create_set_count(&(loot_pool__4->loot_functions[1]), 2, 4);
    LootPool* loot_pool__5 = &(context.loot_pools[5]);
}

LootTableContext* init_buried_treasure_1_18() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
