// this file is automatically generated, do not edit!
#include "desert_pyramid_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[21] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:emerald", "minecraft:bone", "minecraft:spider_eye", "minecraft:rotten_flesh", "minecraft:leather", "minecraft:copper_horse_armor", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:book", "minecraft:golden_apple", "minecraft:enchanted_golden_apple", "minecraft:bone", "minecraft:gunpowder", "minecraft:rotten_flesh", "minecraft:string", "minecraft:sand", "minecraft:dune_armor_trim_smithing_template"};
static int global_item_ids[21] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_EMERALD, ITEM_BONE, ITEM_SPIDER_EYE, ITEM_ROTTEN_FLESH, ITEM_LEATHER, ITEM_COPPER_HORSE_ARMOR, ITEM_IRON_HORSE_ARMOR, ITEM_GOLDEN_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_BOOK, ITEM_GOLDEN_APPLE, ITEM_ENCHANTED_GOLDEN_APPLE, ITEM_BONE, ITEM_GUNPOWDER, ITEM_ROTTEN_FLESH, ITEM_STRING, ITEM_SAND, ITEM_DUNE_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[247] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15};
static int entry_to_item__0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, -1};
static int entry_functions_count__0[16] = {1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0};
static int entry_functions_index__0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 8, 9, 9, 9};
static LootFunction loot_functions__0[9];
static const LootPool desert_pyramid_1_21_11__0 = {
    .min_rolls = 2,
    .max_rolls = 4,
    .roll_count_function = roll_count_uniform,
    .entry_count = 16,
    .total_weight = 247,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[50] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4};
static int entry_to_item__1[5] = {4, 16, 6, 18, 19};
static int entry_functions_count__1[5] = {1, 1, 1, 1, 1};
static int entry_functions_index__1[5] = {0, 1, 2, 3, 4};
static LootFunction loot_functions__1[5];
static const LootPool desert_pyramid_1_21_11__1 = {
    .min_rolls = 4,
    .max_rolls = 4,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 50,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[7] = {0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__2[2] = {-1, 20};
static int entry_functions_count__2[2] = {0, 1};
static int entry_functions_index__2[2] = {0, 0};
static LootFunction loot_functions__2[1];
static const LootPool desert_pyramid_1_21_11__2 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 7,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static LootPool loot_pools[3] = {desert_pyramid_1_21_11__0, desert_pyramid_1_21_11__1, desert_pyramid_1_21_11__2};
static LootTableContext context = {
    .version = MC_1_21_11,
    .item_count = 21,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[4]), 4, 6);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[6]), 3, 7);
    create_set_count(&(loot_pool__0->loot_functions[7]), 1, 5);
    create_enchant_randomly_tag(&(loot_pool__0->loot_functions[8]), MC_1_21_11, get_item_type("minecraft:book"), "#minecraft:on_random_loot", 0);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 8);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 8);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 8);
    create_set_count(&(loot_pool__1->loot_functions[3]), 1, 8);
    create_set_count(&(loot_pool__1->loot_functions[4]), 1, 8);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 2, 2);
}

LootTableContext* init_desert_pyramid_1_21_11() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}

