// this file is automatically generated, do not edit!
#ifndef DESERT_PYRAMID_1_21_11_H
#define DESERT_PYRAMID_1_21_11_H

#include "../loot_table_context.h"

LootTableContext* init_desert_pyramid_1_21_11();

#endif //DESERT_PYRAMID_1_21_11_H
