// this file is automatically generated, do not edit!
#ifndef END_CITY_TREASURE_1_20_H
#define END_CITY_TREASURE_1_20_H

#include "../loot_table_context.h"

void init_end_city_treasure_1_20(LootTableContext* context);

#endif //END_CITY_TREASURE_1_20_H
