// this file is automatically generated, do not edit!
#include "end_city_treasure_1_20.h"

#include "../../biomes.h"

#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_end_city_treasure_1_20(LootTableContext* context) {
    static char* item_names[24] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:emerald", "minecraft:beetroot_seeds", "minecraft:saddle", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:diamond_sword", "minecraft:diamond_boots", "minecraft:diamond_chestplate", "minecraft:diamond_leggings", "minecraft:diamond_helmet", "minecraft:diamond_pickaxe", "minecraft:diamond_shovel", "minecraft:iron_sword", "minecraft:iron_boots", "minecraft:iron_chestplate", "minecraft:iron_leggings", "minecraft:iron_helmet", "minecraft:iron_pickaxe", "minecraft:iron_shovel", "minecraft:spire_armor_trim_smithing_template"};
    static int precomputed_loot__0[85] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 6, 7, 8, 9, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22};
    static int entry_to_item__0[23] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
    static int entry_functions_count__0[23] = {1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
    static int entry_functions_index__0[23] = {0, 1, 2, 3, 4, 5, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
    static LootPool end_city_treasure_1_20__0 = {
        .min_rolls = 2,
        .max_rolls = 6,
        .roll_count_function = roll_count_uniform,
        .entry_count = 23,
        .total_weight = 85,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__1[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
    static int entry_to_item__1[2] = {-1, 23};
    static int entry_functions_count__1[2] = {0, 0};
    static int entry_functions_index__1[2] = {0, 0};
    static LootPool end_city_treasure_1_20__1 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 2,
        .total_weight = 15,
        .precomputed_loot = precomputed_loot__1,
        .entry_to_item = entry_to_item__1,
        .entry_functions_count = entry_functions_count__1,
        .entry_functions_index = entry_functions_index__1,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_20;
    context->item_count = 24;
    context->item_names = item_names;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 2;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = end_city_treasure_1_20__0;
    context->loot_pools[1] = end_city_treasure_1_20__1;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(19 * sizeof(LootFunction));
    create_set_count(&(loot_pool__0->loot_functions[0]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[1]), 4, 8);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[3]), 2, 6);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 10);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[5]), MC_1_20, "minecraft:diamond_sword", get_item_type("minecraft:diamond_sword"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[6]), MC_1_20, "minecraft:diamond_boots", get_item_type("minecraft:diamond_boots"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[7]), MC_1_20, "minecraft:diamond_chestplate", get_item_type("minecraft:diamond_chestplate"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[8]), MC_1_20, "minecraft:diamond_leggings", get_item_type("minecraft:diamond_leggings"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[9]), MC_1_20, "minecraft:diamond_helmet", get_item_type("minecraft:diamond_helmet"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[10]), MC_1_20, "minecraft:diamond_pickaxe", get_item_type("minecraft:diamond_pickaxe"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[11]), MC_1_20, "minecraft:diamond_shovel", get_item_type("minecraft:diamond_shovel"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[12]), MC_1_20, "minecraft:iron_sword", get_item_type("minecraft:iron_sword"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[13]), MC_1_20, "minecraft:iron_boots", get_item_type("minecraft:iron_boots"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[14]), MC_1_20, "minecraft:iron_chestplate", get_item_type("minecraft:iron_chestplate"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[15]), MC_1_20, "minecraft:iron_leggings", get_item_type("minecraft:iron_leggings"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[16]), MC_1_20, "minecraft:iron_helmet", get_item_type("minecraft:iron_helmet"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[17]), MC_1_20, "minecraft:iron_pickaxe", get_item_type("minecraft:iron_pickaxe"), 20, 39, 1);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[18]), MC_1_20, "minecraft:iron_shovel", get_item_type("minecraft:iron_shovel"), 20, 39, 1);
    LootPool* loot_pool__1 = &(context->loot_pools[1]);
    loot_pool__1->loot_functions = malloc(0 * sizeof(LootFunction));
}
