// this file is automatically generated, do not edit!
#ifndef END_CITY_TREASURE_1_20_H
#define END_CITY_TREASURE_1_20_H

#include "../loot_table_context.h"

LootTableContext* init_end_city_treasure_1_20();

#endif //END_CITY_TREASURE_1_20_H
