// this file is automatically generated, do not edit!
#ifndef IGLOO_CHEST_1_13_H
#define IGLOO_CHEST_1_13_H

#include "../loot_table_context.h"

void init_igloo_chest_1_13(LootTableContext* context);

#endif //IGLOO_CHEST_1_13_H
