// this file is automatically generated, do not edit!
#ifndef IGLOO_CHEST_1_13_H
#define IGLOO_CHEST_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_igloo_chest_1_13();

#endif //IGLOO_CHEST_1_13_H
