// this file is automatically generated, do not edit!
#ifndef JUNGLE_TEMPLE_1_21_9_H
#define JUNGLE_TEMPLE_1_21_9_H

#include "../loot_table_context.h"

void init_jungle_temple_1_21_9(LootTableContext* context);

#endif //JUNGLE_TEMPLE_1_21_9_H
