// this file is automatically generated, do not edit!
#include "jungle_temple_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[14] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:bamboo", "minecraft:emerald", "minecraft:bone", "minecraft:rotten_flesh", "minecraft:leather", "minecraft:copper_horse_armor", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:book", "minecraft:wild_armor_trim_smithing_template"};
static int global_item_ids[14] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_BAMBOO, ITEM_EMERALD, ITEM_BONE, ITEM_ROTTEN_FLESH, ITEM_LEATHER, ITEM_COPPER_HORSE_ARMOR, ITEM_IRON_HORSE_ARMOR, ITEM_GOLDEN_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_BOOK, ITEM_WILD_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[89] = {0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 8, 9, 10, 11, 12};
static int entry_to_item__0[13] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static int entry_functions_count__0[13] = {1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1};
static int entry_functions_index__0[13] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 8, 8, 8};
static LootFunction loot_functions__0[9];
static const LootPool jungle_temple_1_21_11__0 = {
    .min_rolls = 2,
    .max_rolls = 6,
    .roll_count_function = roll_count_uniform,
    .entry_count = 13,
    .total_weight = 89,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[3] = {0, 0, 1};
static int entry_to_item__1[2] = {-1, 13};
static int entry_functions_count__1[2] = {0, 1};
static int entry_functions_index__1[2] = {0, 0};
static LootFunction loot_functions__1[1];
static const LootPool jungle_temple_1_21_11__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 3,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {jungle_temple_1_21_11__0, jungle_temple_1_21_11__1};
static LootTableContext context = {
    .version = MC_1_21_11,
    .item_count = 14,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 4, 6);
    create_set_count(&(loot_pool__0->loot_functions[6]), 3, 7);
    create_set_count(&(loot_pool__0->loot_functions[7]), 1, 5);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[8]), MC_1_21_11, "minecraft:book", get_item_type("minecraft:book"), 30, 30, "#minecraft:on_random_loot", 1);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 2, 2);
}

LootTableContext* init_jungle_temple_1_21_11() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}

