// this file is automatically generated, do not edit!
#include "jungle_temple_dispenser_1_13.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_jungle_temple_dispenser_1_13(LootTableContext* context) {
    static char* item_names[1] = {"minecraft:arrow"};
    static int global_item_ids[1] = {ITEM_ARROW};
    static int precomputed_loot__0[30] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    static int entry_to_item__0[1] = {0};
    static int entry_functions_count__0[1] = {1};
    static int entry_functions_index__0[1] = {0};
    static LootPool jungle_temple_dispenser_1_13__0 = {
        .min_rolls = 1,
        .max_rolls = 2,
        .roll_count_function = roll_count_uniform,
        .entry_count = 1,
        .total_weight = 30,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_13;
    context->item_count = 1;
    context->item_names = item_names;
    context->global_item_ids = global_item_ids;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 1;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = jungle_temple_dispenser_1_13__0;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(1 * sizeof(LootFunction));
    create_set_count(&(loot_pool__0->loot_functions[0]), 2, 7);
}
