// this file is automatically generated, do not edit!
#include "jungle_temple_1_20.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_jungle_temple_1_20(LootTableContext* context) {
    static char* item_names[13] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:bamboo", "minecraft:emerald", "minecraft:bone", "minecraft:rotten_flesh", "minecraft:saddle", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:book", "minecraft:wild_armor_trim_smithing_template"};
    static int global_item_ids[13] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_BAMBOO, ITEM_EMERALD, ITEM_BONE, ITEM_ROTTEN_FLESH, ITEM_SADDLE, ITEM_IRON_HORSE_ARMOR, ITEM_GOLDEN_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_BOOK, ITEM_WILD_ARMOR_TRIM_SMITHING_TEMPLATE};
    static int precomputed_loot__0[88] = {0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 8, 9, 10, 11};
    static int entry_to_item__0[12] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
    static int entry_functions_count__0[12] = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1};
    static int entry_functions_index__0[12] = {0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7};
    static LootPool jungle_temple_1_20__0 = {
        .min_rolls = 2,
        .max_rolls = 6,
        .roll_count_function = roll_count_uniform,
        .entry_count = 12,
        .total_weight = 88,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__1[3] = {0, 0, 1};
    static int entry_to_item__1[2] = {-1, 12};
    static int entry_functions_count__1[2] = {0, 1};
    static int entry_functions_index__1[2] = {0, 0};
    static LootPool jungle_temple_1_20__1 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 2,
        .total_weight = 3,
        .precomputed_loot = precomputed_loot__1,
        .entry_to_item = entry_to_item__1,
        .entry_functions_count = entry_functions_count__1,
        .entry_functions_index = entry_functions_index__1,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_20;
    context->item_count = 13;
    context->item_names = item_names;
    context->global_item_ids = global_item_ids;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 2;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = jungle_temple_1_20__0;
    context->loot_pools[1] = jungle_temple_1_20__1;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(8 * sizeof(LootFunction));
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 4, 6);
    create_set_count(&(loot_pool__0->loot_functions[6]), 3, 7);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[7]), MC_1_20, "minecraft:book", get_item_type("minecraft:book"), 30, 30, 1);
    LootPool* loot_pool__1 = &(context->loot_pools[1]);
    loot_pool__1->loot_functions = malloc(1 * sizeof(LootFunction));
    create_set_count(&(loot_pool__1->loot_functions[0]), 2, 2);
}
