// this file is automatically generated, do not edit!
#ifndef JUNGLE_TEMPLE_1_20_H
#define JUNGLE_TEMPLE_1_20_H

#include "../loot_table_context.h"

LootTableContext* init_jungle_temple_1_20();

#endif //JUNGLE_TEMPLE_1_20_H
