// this file is automatically generated, do not edit!
#ifndef JUNGLE_TEMPLE_DISPENSER_1_13_H
#define JUNGLE_TEMPLE_DISPENSER_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_jungle_temple_dispenser_1_13();

#endif //JUNGLE_TEMPLE_DISPENSER_1_13_H
