// this file is automatically generated, do not edit!
#include <pthread.h>

#include "jungle_temple_1_14.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[12] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:bamboo", "minecraft:emerald", "minecraft:bone", "minecraft:rotten_flesh", "minecraft:saddle", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:book"};
static int global_item_ids[12] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_BAMBOO, ITEM_EMERALD, ITEM_BONE, ITEM_ROTTEN_FLESH, ITEM_SADDLE, ITEM_IRON_HORSE_ARMOR, ITEM_GOLDEN_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_BOOK};

static int precomputed_loot__0[88] = {0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 8, 9, 10, 11};
static int entry_to_item__0[12] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static int entry_functions_count__0[12] = {1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1};
static int entry_functions_index__0[12] = {0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 7};
static LootFunction loot_functions__0[8];
static const LootPool jungle_temple_1_14__0 = {
    .min_rolls = 2,
    .max_rolls = 6,
    .roll_count_function = roll_count_uniform,
    .entry_count = 12,
    .total_weight = 88,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {jungle_temple_1_14__0};
static LootTableContext context = {
    .version = MC_1_14,
    .item_count = 12,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 2, 7);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 4, 6);
    create_set_count(&(loot_pool__0->loot_functions[6]), 3, 7);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[7]), MC_1_14, "minecraft:book", get_item_type("minecraft:book"), 30, 30, 1);
}

LootTableContext* init_jungle_temple_1_14() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
