// this file is automatically generated, do not edit!
#ifndef NETHER_BRIDGE_1_20_H
#define NETHER_BRIDGE_1_20_H

#include "../loot_table_context.h"

LootTableContext* init_nether_bridge_1_20();

#endif //NETHER_BRIDGE_1_20_H
