// this file is automatically generated, do not edit!
#include <pthread.h>

#include "nether_bridge_1_20.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[13] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:golden_sword", "minecraft:golden_chestplate", "minecraft:flint_and_steel", "minecraft:nether_wart", "minecraft:saddle", "minecraft:golden_horse_armor", "minecraft:iron_horse_armor", "minecraft:diamond_horse_armor", "minecraft:obsidian", "minecraft:rib_armor_trim_smithing_template"};
static int global_item_ids[13] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_GOLDEN_SWORD, ITEM_GOLDEN_CHESTPLATE, ITEM_FLINT_AND_STEEL, ITEM_NETHER_WART, ITEM_SADDLE, ITEM_GOLDEN_HORSE_ARMOR, ITEM_IRON_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_OBSIDIAN, ITEM_RIB_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[73] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 11, 11};
static int entry_to_item__0[12] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static int entry_functions_count__0[12] = {1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1};
static int entry_functions_index__0[12] = {0, 1, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4};
static LootFunction loot_functions__0[5];
static const LootPool nether_bridge_1_20__0 = {
    .min_rolls = 2,
    .max_rolls = 4,
    .roll_count_function = roll_count_uniform,
    .entry_count = 12,
    .total_weight = 73,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[15] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_to_item__1[2] = {-1, 12};
static int entry_functions_count__1[2] = {0, 0};
static int entry_functions_index__1[2] = {0, 0};
static LootFunction loot_functions__1[0];
static const LootPool nether_bridge_1_20__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 15,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {nether_bridge_1_20__0, nether_bridge_1_20__1};
static LootTableContext context = {
    .version = MC_1_20,
    .item_count = 13,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[3]), 3, 7);
    create_set_count(&(loot_pool__0->loot_functions[4]), 2, 4);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
}

LootTableContext* init_nether_bridge_1_20() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
