// this file is automatically generated, do not edit!
#ifndef NETHER_BRIDGE_1_21_9_H
#define NETHER_BRIDGE_1_21_9_H

#include "../loot_table_context.h"

void init_nether_bridge_1_21_9(LootTableContext* context);

#endif //NETHER_BRIDGE_1_21_9_H
