// this file is automatically generated, do not edit!
#ifndef NETHER_BRIDGE_1_13_H
#define NETHER_BRIDGE_1_13_H

#include "../loot_table_context.h"

void init_nether_bridge_1_13(LootTableContext* context);

#endif //NETHER_BRIDGE_1_13_H
