// this file is automatically generated, do not edit!
#ifndef PILLAGER_OUTPOST_1_14_H
#define PILLAGER_OUTPOST_1_14_H

#include "../loot_table_context.h"

void init_pillager_outpost_1_14(LootTableContext* context);

#endif //PILLAGER_OUTPOST_1_14_H
