// this file is automatically generated, do not edit!
#ifndef PILLAGER_OUTPOST_1_21_11_H
#define PILLAGER_OUTPOST_1_21_11_H

#include "../loot_table_context.h"

LootTableContext* init_pillager_outpost_1_21_11();

#endif //PILLAGER_OUTPOST_1_21_11_H

