// this file is automatically generated, do not edit!
#include "pillager_outpost_1_14.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[11] = {"minecraft:crossbow", "minecraft:wheat", "minecraft:potato", "minecraft:carrot", "minecraft:dark_oak_log", "minecraft:experience_bottle", "minecraft:string", "minecraft:arrow", "minecraft:tripwire_hook", "minecraft:iron_ingot", "minecraft:book"};
static int global_item_ids[11] = {ITEM_CROSSBOW, ITEM_WHEAT, ITEM_POTATO, ITEM_CARROT, ITEM_DARK_OAK_LOG, ITEM_EXPERIENCE_BOTTLE, ITEM_STRING, ITEM_ARROW, ITEM_TRIPWIRE_HOOK, ITEM_IRON_INGOT, ITEM_BOOK};

static int precomputed_loot__0[1] = {0};
static int entry_to_item__0[1] = {0};
static int entry_functions_count__0[1] = {0};
static int entry_functions_index__0[1] = {0};
static LootFunction loot_functions__0[0];
static const LootPool pillager_outpost_1_14__0 = {
    .min_rolls = 0,
    .max_rolls = 1,
    .roll_count_function = roll_count_uniform,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[17] = {0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2};
static int entry_to_item__1[3] = {1, 2, 3};
static int entry_functions_count__1[3] = {1, 1, 1};
static int entry_functions_index__1[3] = {0, 1, 2};
static LootFunction loot_functions__1[3];
static const LootPool pillager_outpost_1_14__1 = {
    .min_rolls = 2,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 3,
    .total_weight = 17,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[1] = {0};
static int entry_to_item__2[1] = {4};
static int entry_functions_count__2[1] = {1};
static int entry_functions_index__2[1] = {0};
static LootFunction loot_functions__2[1];
static const LootPool pillager_outpost_1_14__2 = {
    .min_rolls = 1,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};
static int precomputed_loot__3[22] = {0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5};
static int entry_to_item__3[6] = {5, 6, 7, 8, 9, 10};
static int entry_functions_count__3[6] = {0, 1, 1, 1, 1, 1};
static int entry_functions_index__3[6] = {0, 0, 1, 2, 3, 4};
static LootFunction loot_functions__3[5];
static const LootPool pillager_outpost_1_14__3 = {
    .min_rolls = 2,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 6,
    .total_weight = 22,
    .precomputed_loot = precomputed_loot__3,
    .entry_to_item = entry_to_item__3,
    .entry_functions_count = entry_functions_count__3,
    .entry_functions_index = entry_functions_index__3,
    .loot_functions = loot_functions__3,
};

static LootPool loot_pools[4] = {pillager_outpost_1_14__0, pillager_outpost_1_14__1, pillager_outpost_1_14__2, pillager_outpost_1_14__3};
static LootTableContext context = {
    .version = MC_1_14,
    .item_count = 11,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 4,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 3, 5);
    create_set_count(&(loot_pool__1->loot_functions[1]), 2, 5);
    create_set_count(&(loot_pool__1->loot_functions[2]), 3, 5);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 2, 3);
    LootPool* loot_pool__3 = &(context.loot_pools[3]);
    create_set_count(&(loot_pool__3->loot_functions[0]), 1, 6);
    create_set_count(&(loot_pool__3->loot_functions[1]), 2, 7);
    create_set_count(&(loot_pool__3->loot_functions[2]), 1, 3);
    create_set_count(&(loot_pool__3->loot_functions[3]), 1, 3);
    create_enchant_randomly(&(loot_pool__3->loot_functions[4]), MC_1_14, get_item_type("minecraft:book"), 1);
}

LootTableContext* init_pillager_outpost_1_14() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
