// this file is automatically generated, do not edit!
#ifndef RUINED_PORTAL_1_16_1_H
#define RUINED_PORTAL_1_16_1_H

#include "../loot_table_context.h"

LootTableContext* init_ruined_portal_1_16_1();

#endif //RUINED_PORTAL_1_16_1_H
