// this file is automatically generated, do not edit!
#include "shipwreck_treasure_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

void init_shipwreck_treasure_1_21_11(LootTableContext* context) {
    static char* item_names[13] = {"minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:emerald", "minecraft:diamond", "minecraft:experience_bottle", "minecraft:iron_nugget", "minecraft:gold_nugget", "minecraft:lapis_lazuli", "minecraft:coast_armor_trim_smithing_template", "minecraft:copper_nautilus_armor", "minecraft:iron_nautilus_armor", "minecraft:golden_nautilus_armor", "minecraft:diamond_nautilus_armor"};
    static int global_item_ids[13] = {ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_EMERALD, ITEM_DIAMOND, ITEM_EXPERIENCE_BOTTLE, ITEM_IRON_NUGGET, ITEM_GOLD_NUGGET, ITEM_LAPIS_LAZULI, ITEM_COAST_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_COPPER_NAUTILUS_ARMOR, ITEM_IRON_NAUTILUS_ARMOR, ITEM_GOLDEN_NAUTILUS_ARMOR, ITEM_DIAMOND_NAUTILUS_ARMOR};
    static int precomputed_loot__0[150] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4};
    static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
    static int entry_functions_count__0[5] = {1, 1, 1, 0, 0};
    static int entry_functions_index__0[5] = {0, 1, 2, 3, 3};
    static LootPool shipwreck_treasure_1_21_11__0 = {
        .min_rolls = 3,
        .max_rolls = 6,
        .roll_count_function = roll_count_uniform,
        .entry_count = 5,
        .total_weight = 150,
        .precomputed_loot = precomputed_loot__0,
        .entry_to_item = entry_to_item__0,
        .entry_functions_count = entry_functions_count__0,
        .entry_functions_index = entry_functions_index__0,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__1[80] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
    static int entry_to_item__1[3] = {5, 6, 7};
    static int entry_functions_count__1[3] = {1, 1, 1};
    static int entry_functions_index__1[3] = {0, 1, 2};
    static LootPool shipwreck_treasure_1_21_11__1 = {
        .min_rolls = 2,
        .max_rolls = 5,
        .roll_count_function = roll_count_uniform,
        .entry_count = 3,
        .total_weight = 80,
        .precomputed_loot = precomputed_loot__1,
        .entry_to_item = entry_to_item__1,
        .entry_functions_count = entry_functions_count__1,
        .entry_functions_index = entry_functions_index__1,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__2[6] = {0, 0, 0, 0, 0, 1};
    static int entry_to_item__2[2] = {-1, 8};
    static int entry_functions_count__2[2] = {0, 1};
    static int entry_functions_index__2[2] = {0, 0};
    static LootPool shipwreck_treasure_1_21_11__2 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 2,
        .total_weight = 6,
        .precomputed_loot = precomputed_loot__2,
        .entry_to_item = entry_to_item__2,
        .entry_functions_count = entry_functions_count__2,
        .entry_functions_index = entry_functions_index__2,
        .loot_functions = NULL, // initialised later
    };
    static int precomputed_loot__3[185] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4};
    static int entry_to_item__3[5] = {-1, 9, 10, 11, 12};
    static int entry_functions_count__3[5] = {0, 1, 1, 1, 1};
    static int entry_functions_index__3[5] = {0, 0, 1, 2, 3};
    static LootPool shipwreck_treasure_1_21_11__3 = {
        .min_rolls = 1,
        .max_rolls = 1,
        .roll_count_function = roll_count_constant,
        .entry_count = 5,
        .total_weight = 185,
        .precomputed_loot = precomputed_loot__3,
        .entry_to_item = entry_to_item__3,
        .entry_functions_count = entry_functions_count__3,
        .entry_functions_index = entry_functions_index__3,
        .loot_functions = NULL, // initialised later
    };

    context->version = MC_1_21_11;
    context->item_count = 13;
    context->item_names = item_names;
    context->global_item_ids = global_item_ids;

    context->unresolved_subtable_count = 0;
    context->subtable_count = 0;
    context->subtable_pool_offset = NULL;
    context->subtable_pool_count = NULL;

    context->pool_count = 4;
    context->loot_pools = malloc(context->pool_count * sizeof(LootPool));
    context->loot_pools[0] = shipwreck_treasure_1_21_11__0;
    context->loot_pools[1] = shipwreck_treasure_1_21_11__1;
    context->loot_pools[2] = shipwreck_treasure_1_21_11__2;
    context->loot_pools[3] = shipwreck_treasure_1_21_11__3;
    LootPool* loot_pool__0 = &(context->loot_pools[0]);
    loot_pool__0->loot_functions = malloc(3 * sizeof(LootFunction));
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 5);
    LootPool* loot_pool__1 = &(context->loot_pools[1]);
    loot_pool__1->loot_functions = malloc(3 * sizeof(LootFunction));
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 10);
    LootPool* loot_pool__2 = &(context->loot_pools[2]);
    loot_pool__2->loot_functions = malloc(1 * sizeof(LootFunction));
    create_set_count(&(loot_pool__2->loot_functions[0]), 2, 2);
    LootPool* loot_pool__3 = &(context->loot_pools[3]);
    loot_pool__3->loot_functions = malloc(4 * sizeof(LootFunction));
    create_set_count(&(loot_pool__3->loot_functions[0]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[3]), 1, 1);
}
