// this file is automatically generated, do not edit!
#include "shipwreck_map_1_13.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[7] = {"minecraft:map", "minecraft:compass", "minecraft:map", "minecraft:clock", "minecraft:paper", "minecraft:feather", "minecraft:book"};
static int global_item_ids[7] = {ITEM_MAP, ITEM_COMPASS, ITEM_MAP, ITEM_CLOCK, ITEM_PAPER, ITEM_FEATHER, ITEM_BOOK};

static int precomputed_loot__0[1] = {0};
static int entry_to_item__0[1] = {0};
static int entry_functions_count__0[1] = {1};
static int entry_functions_index__0[1] = {0};
static LootFunction loot_functions__0[1];
static const LootPool shipwreck_map_1_13__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[38] = {0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5};
static int entry_to_item__1[6] = {1, 0, 3, 4, 5, 6};
static int entry_functions_count__1[6] = {0, 0, 0, 1, 1, 1};
static int entry_functions_index__1[6] = {0, 0, 0, 0, 1, 2};
static LootFunction loot_functions__1[3];
static const LootPool shipwreck_map_1_13__1 = {
    .min_rolls = 3,
    .max_rolls = 3,
    .roll_count_function = roll_count_constant,
    .entry_count = 6,
    .total_weight = 38,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {shipwreck_map_1_13__0, shipwreck_map_1_13__1};
static LootTableContext context = {
    .version = MC_1_13,
    .item_count = 7,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_no_op(&(loot_pool__0->loot_functions[0]));
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 5);
}

LootTableContext* init_shipwreck_map_1_13() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
