// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_MAP_1_20_H
#define SHIPWRECK_MAP_1_20_H

#include "../loot_table_context.h"

void init_shipwreck_map_1_20(LootTableContext* context);

#endif //SHIPWRECK_MAP_1_20_H
