// this file is automatically generated, do not edit!
#include <pthread.h>

#include "shipwreck_supply_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[22] = {"minecraft:paper", "minecraft:potato", "minecraft:moss_block", "minecraft:poisonous_potato", "minecraft:carrot", "minecraft:wheat", "minecraft:suspicious_stew", "minecraft:coal", "minecraft:rotten_flesh", "minecraft:pumpkin", "minecraft:bamboo", "minecraft:gunpowder", "minecraft:tnt", "minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots", "minecraft:coast_armor_trim_smithing_template", "minecraft:copper_nautilus_armor", "minecraft:iron_nautilus_armor", "minecraft:golden_nautilus_armor", "minecraft:diamond_nautilus_armor"};
static int global_item_ids[22] = {ITEM_PAPER, ITEM_POTATO, ITEM_MOSS_BLOCK, ITEM_POISONOUS_POTATO, ITEM_CARROT, ITEM_WHEAT, ITEM_SUSPICIOUS_STEW, ITEM_COAL, ITEM_ROTTEN_FLESH, ITEM_PUMPKIN, ITEM_BAMBOO, ITEM_GUNPOWDER, ITEM_TNT, ITEM_LEATHER_HELMET, ITEM_LEATHER_CHESTPLATE, ITEM_LEATHER_LEGGINGS, ITEM_LEATHER_BOOTS, ITEM_COAST_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_COPPER_NAUTILUS_ARMOR, ITEM_IRON_NAUTILUS_ARMOR, ITEM_GOLDEN_NAUTILUS_ARMOR, ITEM_DIAMOND_NAUTILUS_ARMOR};

static int precomputed_loot__0[84] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 10, 10, 11, 11, 11, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16};
static int entry_to_item__0[17] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static int entry_functions_count__0[17] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__0[17] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static LootFunction loot_functions__0[17];
static const LootPool shipwreck_supply_1_21_11__0 = {
    .min_rolls = 3,
    .max_rolls = 10,
    .roll_count_function = roll_count_uniform,
    .entry_count = 17,
    .total_weight = 84,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[6] = {0, 0, 0, 0, 0, 1};
static int entry_to_item__1[2] = {-1, 17};
static int entry_functions_count__1[2] = {0, 1};
static int entry_functions_index__1[2] = {0, 0};
static LootFunction loot_functions__1[1];
static const LootPool shipwreck_supply_1_21_11__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 6,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[185] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4};
static int entry_to_item__2[5] = {-1, 18, 19, 20, 21};
static int entry_functions_count__2[5] = {0, 1, 1, 1, 1};
static int entry_functions_index__2[5] = {0, 0, 1, 2, 3};
static LootFunction loot_functions__2[4];
static const LootPool shipwreck_supply_1_21_11__2 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 185,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static LootPool loot_pools[3] = {shipwreck_supply_1_21_11__0, shipwreck_supply_1_21_11__1, shipwreck_supply_1_21_11__2};
static LootTableContext context = {
    .version = MC_1_21_11,
    .item_count = 22,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 12);
    create_set_count(&(loot_pool__0->loot_functions[1]), 2, 6);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[3]), 2, 6);
    create_set_count(&(loot_pool__0->loot_functions[4]), 4, 8);
    create_set_count(&(loot_pool__0->loot_functions[5]), 8, 21);
    create_set_effect(&(loot_pool__0->loot_functions[6]));
    create_set_count(&(loot_pool__0->loot_functions[7]), 2, 8);
    create_set_count(&(loot_pool__0->loot_functions[8]), 5, 24);
    create_set_count(&(loot_pool__0->loot_functions[9]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[10]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[11]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[12]), 1, 2);
    create_enchant_randomly(&(loot_pool__0->loot_functions[13]), MC_1_21_11, get_item_type("minecraft:leather_helmet"), 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[14]), MC_1_21_11, get_item_type("minecraft:leather_chestplate"), 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[15]), MC_1_21_11, get_item_type("minecraft:leather_leggings"), 1);
    create_enchant_randomly(&(loot_pool__0->loot_functions[16]), MC_1_21_11, get_item_type("minecraft:leather_boots"), 1);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 2, 2);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 1, 1);
    create_set_count(&(loot_pool__2->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__2->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__2->loot_functions[3]), 1, 1);
}

LootTableContext* init_shipwreck_supply_1_21_11() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
