// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_MAP_1_21_11_H
#define SHIPWRECK_MAP_1_21_11_H

#include "../loot_table_context.h"

LootTableContext* init_shipwreck_map_1_21_11();

#endif //SHIPWRECK_MAP_1_21_11_H
