// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_TREASURE_1_21_11_H
#define SHIPWRECK_TREASURE_1_21_11_H

#include "../loot_table_context.h"

void init_shipwreck_treasure_1_21_11(LootTableContext* context);

#endif //SHIPWRECK_TREASURE_1_21_11_H
