// this file is automatically generated, do not edit!
#include "shipwreck_map_1_21_11.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[12] = {"minecraft:map", "minecraft:compass", "minecraft:map", "minecraft:clock", "minecraft:paper", "minecraft:feather", "minecraft:book", "minecraft:coast_armor_trim_smithing_template", "minecraft:copper_nautilus_armor", "minecraft:iron_nautilus_armor", "minecraft:golden_nautilus_armor", "minecraft:diamond_nautilus_armor"};
static int global_item_ids[12] = {ITEM_MAP, ITEM_COMPASS, ITEM_MAP, ITEM_CLOCK, ITEM_PAPER, ITEM_FEATHER, ITEM_BOOK, ITEM_COAST_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_COPPER_NAUTILUS_ARMOR, ITEM_IRON_NAUTILUS_ARMOR, ITEM_GOLDEN_NAUTILUS_ARMOR, ITEM_DIAMOND_NAUTILUS_ARMOR};

static int precomputed_loot__0[1] = {0};
static int entry_to_item__0[1] = {0};
static int entry_functions_count__0[1] = {2};
static int entry_functions_index__0[1] = {0};
static LootFunction loot_functions__0[2];
static const LootPool shipwreck_map_1_21_11__0 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[38] = {0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5};
static int entry_to_item__1[6] = {1, 0, 3, 4, 5, 6};
static int entry_functions_count__1[6] = {0, 0, 0, 1, 1, 1};
static int entry_functions_index__1[6] = {0, 0, 0, 0, 1, 2};
static LootFunction loot_functions__1[3];
static const LootPool shipwreck_map_1_21_11__1 = {
    .min_rolls = 3,
    .max_rolls = 3,
    .roll_count_function = roll_count_constant,
    .entry_count = 6,
    .total_weight = 38,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[6] = {0, 0, 0, 0, 0, 1};
static int entry_to_item__2[2] = {-1, 7};
static int entry_functions_count__2[2] = {0, 1};
static int entry_functions_index__2[2] = {0, 0};
static LootFunction loot_functions__2[1];
static const LootPool shipwreck_map_1_21_11__2 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 6,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};
static int precomputed_loot__3[185] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4};
static int entry_to_item__3[5] = {-1, 8, 9, 10, 11};
static int entry_functions_count__3[5] = {0, 1, 1, 1, 1};
static int entry_functions_index__3[5] = {0, 0, 1, 2, 3};
static LootFunction loot_functions__3[4];
static const LootPool shipwreck_map_1_21_11__3 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 185,
    .precomputed_loot = precomputed_loot__3,
    .entry_to_item = entry_to_item__3,
    .entry_functions_count = entry_functions_count__3,
    .entry_functions_index = entry_functions_index__3,
    .loot_functions = loot_functions__3,
};

static LootPool loot_pools[4] = {shipwreck_map_1_21_11__0, shipwreck_map_1_21_11__1, shipwreck_map_1_21_11__2, shipwreck_map_1_21_11__3};
static LootTableContext context = {
    .version = MC_1_21_11,
    .item_count = 12,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 4,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_no_op(&(loot_pool__0->loot_functions[0]));
    create_no_op(&(loot_pool__0->loot_functions[1]));
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 5);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 2, 2);
    LootPool* loot_pool__3 = &(context.loot_pools[3]);
    create_set_count(&(loot_pool__3->loot_functions[0]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[1]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[2]), 1, 1);
    create_set_count(&(loot_pool__3->loot_functions[3]), 1, 1);
}

LootTableContext* init_shipwreck_map_1_21_11() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
