// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_TREASURE_1_13_H
#define SHIPWRECK_TREASURE_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_shipwreck_treasure_1_13();

#endif //SHIPWRECK_TREASURE_1_13_H
