// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_TREASURE_1_20_H
#define SHIPWRECK_TREASURE_1_20_H

#include "../loot_table_context.h"

void init_shipwreck_treasure_1_20(LootTableContext* context);

#endif //SHIPWRECK_TREASURE_1_20_H
