// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_SUPPLY_1_13_H
#define SHIPWRECK_SUPPLY_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_shipwreck_supply_1_13();

#endif //SHIPWRECK_SUPPLY_1_13_H
