// this file is automatically generated, do not edit!
#include <pthread.h>

#include "shipwreck_treasure_1_20.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static pthread_once_t control = PTHREAD_ONCE_INIT;

static char* item_names[9] = {"minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:emerald", "minecraft:diamond", "minecraft:experience_bottle", "minecraft:iron_nugget", "minecraft:gold_nugget", "minecraft:lapis_lazuli", "minecraft:coast_armor_trim_smithing_template"};
static int global_item_ids[9] = {ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_EMERALD, ITEM_DIAMOND, ITEM_EXPERIENCE_BOTTLE, ITEM_IRON_NUGGET, ITEM_GOLD_NUGGET, ITEM_LAPIS_LAZULI, ITEM_COAST_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[150] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
static int entry_functions_count__0[5] = {1, 1, 1, 0, 0};
static int entry_functions_index__0[5] = {0, 1, 2, 3, 3};
static LootFunction loot_functions__0[3];
static const LootPool shipwreck_treasure_1_20__0 = {
    .min_rolls = 3,
    .max_rolls = 6,
    .roll_count_function = roll_count_uniform,
    .entry_count = 5,
    .total_weight = 150,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[80] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
static int entry_to_item__1[3] = {5, 6, 7};
static int entry_functions_count__1[3] = {1, 1, 1};
static int entry_functions_index__1[3] = {0, 1, 2};
static LootFunction loot_functions__1[3];
static const LootPool shipwreck_treasure_1_20__1 = {
    .min_rolls = 2,
    .max_rolls = 5,
    .roll_count_function = roll_count_uniform,
    .entry_count = 3,
    .total_weight = 80,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static int precomputed_loot__2[6] = {0, 0, 0, 0, 0, 1};
static int entry_to_item__2[2] = {-1, 8};
static int entry_functions_count__2[2] = {0, 1};
static int entry_functions_index__2[2] = {0, 0};
static LootFunction loot_functions__2[1];
static const LootPool shipwreck_treasure_1_20__2 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 6,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static LootPool loot_pools[3] = {shipwreck_treasure_1_20__0, shipwreck_treasure_1_20__1, shipwreck_treasure_1_20__2};
static LootTableContext context = {
    .version = MC_1_20,
    .item_count = 9,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

static void create_loot_functions(void) {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 5);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_set_count(&(loot_pool__1->loot_functions[0]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[1]), 1, 10);
    create_set_count(&(loot_pool__1->loot_functions[2]), 1, 10);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_set_count(&(loot_pool__2->loot_functions[0]), 2, 2);
}

LootTableContext* init_shipwreck_treasure_1_20() {
    pthread_once(&control, create_loot_functions);
    return &context;
}
