// this file is automatically generated, do not edit!
#ifndef SHIPWRECK_TREASURE_1_13_H
#define SHIPWRECK_TREASURE_1_13_H

#include "../loot_table_context.h"

void init_shipwreck_treasure_1_13(LootTableContext* context);

#endif //SHIPWRECK_TREASURE_1_13_H
