// this file is automatically generated, do not edit!
#include "stronghold_library_1_20.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[6] = {"minecraft:book", "minecraft:paper", "minecraft:map", "minecraft:compass", "minecraft:book", "minecraft:eye_armor_trim_smithing_template"};
static int global_item_ids[6] = {ITEM_BOOK, ITEM_PAPER, ITEM_MAP, ITEM_COMPASS, ITEM_BOOK, ITEM_EYE_ARMOR_TRIM_SMITHING_TEMPLATE};

static int precomputed_loot__0[52] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 0};
static int entry_functions_count__0[5] = {1, 1, 0, 0, 1};
static int entry_functions_index__0[5] = {0, 1, 2, 2, 2};
static LootFunction loot_functions__0[3];
static const LootPool stronghold_library_1_20__0 = {
    .min_rolls = 2,
    .max_rolls = 10,
    .roll_count_function = roll_count_uniform,
    .entry_count = 5,
    .total_weight = 52,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[1] = {0};
static int entry_to_item__1[1] = {5};
static int entry_functions_count__1[1] = {0};
static int entry_functions_index__1[1] = {0};
static LootFunction loot_functions__1[0];
static const LootPool stronghold_library_1_20__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {stronghold_library_1_20__0, stronghold_library_1_20__1};
static LootTableContext context = {
    .version = MC_1_20,
    .item_count = 6,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 2, 7);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[2]), MC_1_20, "minecraft:book", get_item_type("minecraft:book"), 30, 30, 1);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
}

LootTableContext* init_stronghold_library_1_20() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
