// this file is automatically generated, do not edit!
#ifndef STRONGHOLD_CORRIDOR_1_13_H
#define STRONGHOLD_CORRIDOR_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_stronghold_corridor_1_13();

#endif //STRONGHOLD_CORRIDOR_1_13_H
