// this file is automatically generated, do not edit!
#ifndef STRONGHOLD_CORRIDOR_1_21_6_H
#define STRONGHOLD_CORRIDOR_1_21_6_H

#include "../loot_table_context.h"

LootTableContext* init_stronghold_corridor_1_21_6();

#endif //STRONGHOLD_CORRIDOR_1_21_6_H
