// this file is automatically generated, do not edit!
#ifndef STRONGHOLD_LIBRARY_1_13_H
#define STRONGHOLD_LIBRARY_1_13_H

#include "../loot_table_context.h"

LootTableContext* init_stronghold_library_1_13();

#endif //STRONGHOLD_LIBRARY_1_13_H
