// this file is automatically generated, do not edit!
#include "stronghold_corridor_1_18.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[20] = {"minecraft:ender_pearl", "minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:redstone", "minecraft:bread", "minecraft:apple", "minecraft:iron_pickaxe", "minecraft:iron_sword", "minecraft:iron_chestplate", "minecraft:iron_helmet", "minecraft:iron_leggings", "minecraft:iron_boots", "minecraft:golden_apple", "minecraft:saddle", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:music_disc_otherside", "minecraft:book"};
static int global_item_ids[20] = {ITEM_ENDER_PEARL, ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_REDSTONE, ITEM_BREAD, ITEM_APPLE, ITEM_IRON_PICKAXE, ITEM_IRON_SWORD, ITEM_IRON_CHESTPLATE, ITEM_IRON_HELMET, ITEM_IRON_LEGGINGS, ITEM_IRON_BOOTS, ITEM_GOLDEN_APPLE, ITEM_SADDLE, ITEM_IRON_HORSE_ARMOR, ITEM_GOLDEN_HORSE_ARMOR, ITEM_DIAMOND_HORSE_ARMOR, ITEM_MUSIC_DISC_OTHERSIDE, ITEM_BOOK};

static int precomputed_loot__0[100] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19};
static int entry_to_item__0[20] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static int entry_functions_count__0[20] = {0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1};
static int entry_functions_index__0[20] = {0, 0, 1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6};
static LootFunction loot_functions__0[7];
static const LootPool stronghold_corridor_1_18__0 = {
    .min_rolls = 2,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 20,
    .total_weight = 100,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {stronghold_corridor_1_18__0};
static LootTableContext context = {
    .version = MC_1_18,
    .item_count = 20,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[3]), 4, 9);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 3);
    create_enchant_with_levels(&(loot_pool__0->loot_functions[6]), MC_1_18, "minecraft:book", get_item_type("minecraft:book"), 30, 30, 1);
}

LootTableContext* init_stronghold_corridor_1_18() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
