// this file is automatically generated, do not edit!
#ifndef UNDERWATER_RUIN_BIG_1_18_H
#define UNDERWATER_RUIN_BIG_1_18_H

#include "../loot_table_context.h"

LootTableContext* init_underwater_ruin_big_1_18();

#endif //UNDERWATER_RUIN_BIG_1_18_H
