// this file is automatically generated, do not edit!
#include "underwater_ruin_small_1_18.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised = 0;

static char* item_names[9] = {"minecraft:coal", "minecraft:stone_axe", "minecraft:rotten_flesh", "minecraft:emerald", "minecraft:wheat", "minecraft:leather_chestplate", "minecraft:golden_helmet", "minecraft:fishing_rod", "minecraft:map"};
static int global_item_ids[9] = {ITEM_COAL, ITEM_STONE_AXE, ITEM_ROTTEN_FLESH, ITEM_EMERALD, ITEM_WHEAT, ITEM_LEATHER_CHESTPLATE, ITEM_GOLDEN_HELMET, ITEM_FISHING_ROD, ITEM_MAP};

static int precomputed_loot__0[28] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
static int entry_functions_count__0[5] = {1, 0, 0, 0, 1};
static int entry_functions_index__0[5] = {0, 1, 1, 1, 1};
static LootFunction loot_functions__0[2];
static const LootPool underwater_ruin_small_1_18__0 = {
    .min_rolls = 2,
    .max_rolls = 8,
    .roll_count_function = roll_count_uniform,
    .entry_count = 5,
    .total_weight = 28,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static int precomputed_loot__1[12] = {0, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3};
static int entry_to_item__1[4] = {5, 6, 7, 8};
static int entry_functions_count__1[4] = {0, 0, 1, 2};
static int entry_functions_index__1[4] = {0, 0, 0, 1};
static LootFunction loot_functions__1[3];
static const LootPool underwater_ruin_small_1_18__1 = {
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 4,
    .total_weight = 12,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};

static LootPool loot_pools[2] = {underwater_ruin_small_1_18__0, underwater_ruin_small_1_18__1};
static LootTableContext context = {
    .version = MC_1_18,
    .item_count = 9,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 2,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[1]), 2, 3);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    create_enchant_randomly(&(loot_pool__1->loot_functions[0]), MC_1_18, get_item_type("minecraft:fishing_rod"), 0);
    create_no_op(&(loot_pool__1->loot_functions[1]));
    create_no_op(&(loot_pool__1->loot_functions[2]));
}

LootTableContext* init_underwater_ruin_small_1_18() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
