// this file is automatically generated, do not edit!
#ifndef VILLAGE_SHEPHERD_1_16_1_H
#define VILLAGE_SHEPHERD_1_16_1_H

#include "../loot_table_context.h"

LootTableContext* init_village_shepherd_1_16_1(int version);

#endif //VILLAGE_SHEPHERD_1_16_1_H
