// this file is automatically generated, do not edit!
#include "village_temple_1_16_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised_version = 0;

static char* item_names[6] = {"minecraft:redstone", "minecraft:bread", "minecraft:rotten_flesh", "minecraft:lapis_lazuli", "minecraft:gold_ingot", "minecraft:emerald"};
static int global_item_ids[6] = {ITEM_REDSTONE, ITEM_BREAD, ITEM_ROTTEN_FLESH, ITEM_LAPIS_LAZULI, ITEM_GOLD_INGOT, ITEM_EMERALD};

static int precomputed_loot__0[19] = {0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5};
static int entry_to_item__0[6] = {0, 1, 2, 3, 4, 5};
static int entry_functions_count__0[6] = {1, 1, 1, 1, 1, 1};
static int entry_functions_index__0[6] = {0, 1, 2, 3, 4, 5};
static LootFunction loot_functions__0[6];
static const LootPool village_temple_1_16_1__0 = {
    .min_rolls = 3,
    .max_rolls = 8,
    .roll_count_function = roll_count_uniform,
    .entry_count = 6,
    .total_weight = 19,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {village_temple_1_16_1__0};
static LootTableContext context = {
    .version = 0, // set by init
    .item_count = 6,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions(int version) {
    (void)version; // unused when the table has no enchantment functions
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 4);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 4);
}

LootTableContext* init_village_temple_1_16_1(int version) {
    // Rebuild if the requested version differs: enchantment registries are
    // version dependent, and one table file serves a range of versions.
    if (initialised_version != version) {
        context.version = version;
        create_loot_functions(version);
        initialised_version = version;
    }
    return &context;
}
