// this file is automatically generated, do not edit!
#include "village_toolsmith_1_16_1.h"

#include "../../biomes.h"

#include "../items.h"
#include "../loot_table_context.h"
#include "../loot_table_parser.h"

static int initialised_version = 0;

static char* item_names[8] = {"minecraft:diamond", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:bread", "minecraft:iron_pickaxe", "minecraft:coal", "minecraft:stick", "minecraft:iron_shovel"};
static int global_item_ids[8] = {ITEM_DIAMOND, ITEM_IRON_INGOT, ITEM_GOLD_INGOT, ITEM_BREAD, ITEM_IRON_PICKAXE, ITEM_COAL, ITEM_STICK, ITEM_IRON_SHOVEL};

static int precomputed_loot__0[53] = {0, 1, 1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7};
static int entry_to_item__0[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static int entry_functions_count__0[8] = {1, 1, 1, 1, 0, 1, 1, 0};
static int entry_functions_index__0[8] = {0, 1, 2, 3, 4, 4, 5, 6};
static LootFunction loot_functions__0[6];
static const LootPool village_toolsmith_1_16_1__0 = {
    .min_rolls = 3,
    .max_rolls = 8,
    .roll_count_function = roll_count_uniform,
    .entry_count = 8,
    .total_weight = 53,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {village_toolsmith_1_16_1__0};
static LootTableContext context = {
    .version = 0, // set by init
    .item_count = 8,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions(int version) {
    (void)version; // unused when the table has no enchantment functions
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[1]), 1, 5);
    create_set_count(&(loot_pool__0->loot_functions[2]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[3]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[4]), 1, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 3);
}

LootTableContext* init_village_toolsmith_1_16_1(int version) {
    // Rebuild if the requested version differs: enchantment registries are
    // version dependent, and one table file serves a range of versions.
    if (initialised_version != version) {
        context.version = version;
        create_loot_functions(version);
        initialised_version = version;
    }
    return &context;
}
