// this file is automatically generated, do not edit!
#ifndef ABANDONED_CAMP_BARREL_26_3_H
#define ABANDONED_CAMP_BARREL_26_3_H

#include "../../loot_table_context.h"

LootTableContext* init_abandoned_camp_barrel_26_3();

#endif //ABANDONED_CAMP_BARREL_26_3_H
