// this file is automatically generated, do not edit!
#include "reward_rare_1_21_1.h"

#include "../../../../biomes.h"

#include "../../../items.h"
#include "../../../loot_table_context.h"
#include "../../../loot_table_parser.h"

static int initialised = 0;

static char* item_names[11] = {"minecraft:emerald", "minecraft:shield", "minecraft:bow", "minecraft:crossbow", "minecraft:iron_axe", "minecraft:iron_chestplate", "minecraft:golden_carrot", "minecraft:book", "minecraft:book", "minecraft:diamond_chestplate", "minecraft:diamond_axe"};
static int global_item_ids[11] = {ITEM_EMERALD, ITEM_SHIELD, ITEM_BOW, ITEM_CROSSBOW, ITEM_IRON_AXE, ITEM_IRON_CHESTPLATE, ITEM_GOLDEN_CARROT, ITEM_BOOK, ITEM_BOOK, ITEM_DIAMOND_CHESTPLATE, ITEM_DIAMOND_AXE};

static LootItemCondition conditions__0[0];
static int precomputed_loot__0[23] = {0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 10};
static int entry_to_item__0[11] = {0, 1, 2, 3, 4, 5, 6, 7, 7, 9, 10};
static int entry_functions_count__0[11] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static int entry_functions_index__0[11] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static LootFunction loot_functions__0[11];
static const LootPool reward_rare_1_21_1__0 = {
    .condition_count = 0,
    .conditions = conditions__0,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 11,
    .total_weight = 23,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {reward_rare_1_21_1__0};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 11,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 2, 4);
    create_skip_calls(&(loot_pool__0->loot_functions[1]), 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[2]), MC_1_21_1, "minecraft:bow", get_item_type("minecraft:bow"), 5, 15, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[3]), MC_1_21_1, "minecraft:crossbow", get_item_type("minecraft:crossbow"), 5, 20, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[4]), MC_1_21_1, "minecraft:iron_axe", get_item_type("minecraft:iron_axe"), 0, 10, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[5]), MC_1_21_1, "minecraft:iron_chestplate", get_item_type("minecraft:iron_chestplate"), 0, 10, "#minecraft:on_random_loot", 1);
    create_set_count(&(loot_pool__0->loot_functions[6]), 1, 2);
    create_enchant_randomly_list(&(loot_pool__0->loot_functions[7]), (Enchantment[]){get_enchantment_from_name("minecraft:sharpness"), get_enchantment_from_name("minecraft:bane_of_arthropods"), get_enchantment_from_name("minecraft:efficiency"), get_enchantment_from_name("minecraft:fortune"), get_enchantment_from_name("minecraft:silk_touch"), get_enchantment_from_name("minecraft:feather_falling")}, 6);
    create_enchant_randomly_list(&(loot_pool__0->loot_functions[8]), (Enchantment[]){get_enchantment_from_name("minecraft:riptide"), get_enchantment_from_name("minecraft:loyalty"), get_enchantment_from_name("minecraft:channeling"), get_enchantment_from_name("minecraft:impaling"), get_enchantment_from_name("minecraft:mending")}, 5);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[9]), MC_1_21_1, "minecraft:diamond_chestplate", get_item_type("minecraft:diamond_chestplate"), 5, 15, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[10]), MC_1_21_1, "minecraft:diamond_axe", get_item_type("minecraft:diamond_axe"), 5, 15, "#minecraft:on_random_loot", 1);
}

LootTableContext* init_reward_rare_1_21_1() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
