// this file is automatically generated, do not edit!
#include "reward_unique_1_21_1.h"

#include "../../../../biomes.h"

#include "../../../items.h"
#include "../../../loot_table_context.h"
#include "../../../loot_table_parser.h"

static int initialised = 0;

static char* item_names[5] = {"minecraft:golden_apple", "minecraft:bolt_armor_trim_smithing_template", "minecraft:guster_banner_pattern", "minecraft:music_disc_precipice", "minecraft:trident"};
static int global_item_ids[5] = {ITEM_GOLDEN_APPLE, ITEM_BOLT_ARMOR_TRIM_SMITHING_TEMPLATE, ITEM_GUSTER_BANNER_PATTERN, ITEM_MUSIC_DISC_PRECIPICE, ITEM_TRIDENT};

static LootItemCondition conditions__0[0];
static int precomputed_loot__0[12] = {0, 0, 0, 0, 1, 1, 1, 2, 2, 3, 3, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
static int entry_functions_count__0[5] = {0, 0, 0, 0, 0};
static int entry_functions_index__0[5] = {0, 0, 0, 0, 0};
static LootFunction loot_functions__0[0];
static const LootPool reward_unique_1_21_1__0 = {
    .condition_count = 0,
    .conditions = conditions__0,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 12,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {reward_unique_1_21_1__0};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 5,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
}

LootTableContext* init_reward_unique_1_21_1() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
