// this file is automatically generated, do not edit!
#include "reward_1_21_1.h"

#include "../../../../biomes.h"

#include "../../../items.h"
#include "../../../loot_table_context.h"
#include "../../../loot_table_parser.h"
#include "../../../loot_tables/chests/trial_chambers/reward_rare_1_21_1.h"
#include "../../../loot_tables/chests/trial_chambers/reward_common_1_21_1.h"
#include "../../../loot_tables/chests/trial_chambers/reward_unique_1_21_1.h"

static int initialised = 0;

static char* item_names[0] = {};
static int global_item_ids[0] = {};

static LootItemCondition conditions__0[0];
static int precomputed_loot__0[10] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1};
static int entry_to_item__0[2] = {-2, -3};
static int entry_functions_count__0[2] = {};
static int entry_functions_index__0[2] = {};
static LootFunction loot_functions__0[0];
static const LootPool reward_1_21_1__0 = {
    .condition_count = 0,
    .conditions = conditions__0,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 2,
    .total_weight = 10,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};
static LootItemCondition conditions__1[0];
static int precomputed_loot__1[1] = {0};
static int entry_to_item__1[1] = {-3};
static int entry_functions_count__1[1] = {};
static int entry_functions_index__1[1] = {};
static LootFunction loot_functions__1[0];
static const LootPool reward_1_21_1__1 = {
    .condition_count = 0,
    .conditions = conditions__1,
    .min_rolls = 1,
    .max_rolls = 3,
    .roll_count_function = roll_count_uniform,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__1,
    .entry_to_item = entry_to_item__1,
    .entry_functions_count = entry_functions_count__1,
    .entry_functions_index = entry_functions_index__1,
    .loot_functions = loot_functions__1,
};
static LootItemCondition conditions__2[1];
static int precomputed_loot__2[1] = {0};
static int entry_to_item__2[1] = {-4};
static int entry_functions_count__2[1] = {};
static int entry_functions_index__2[1] = {};
static LootFunction loot_functions__2[0];
static const LootPool reward_1_21_1__2 = {
    .condition_count = 1,
    .conditions = conditions__2,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 1,
    .total_weight = 1,
    .precomputed_loot = precomputed_loot__2,
    .entry_to_item = entry_to_item__2,
    .entry_functions_count = entry_functions_count__2,
    .entry_functions_index = entry_functions_index__2,
    .loot_functions = loot_functions__2,
};

static int subtable_pool_offset[3] = {0};
static int subtable_pool_count[3] = {0};
static LootPool loot_pools[3] = {reward_1_21_1__0, reward_1_21_1__1, reward_1_21_1__2};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 0,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = subtable_pool_offset,
    .subtable_pool_count = subtable_pool_count,
    .pool_count = 3,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    LootPool* loot_pool__1 = &(context.loot_pools[1]);
    LootPool* loot_pool__2 = &(context.loot_pools[2]);
    create_random_chance(&(loot_pool__2->conditions[0]), 0.25f);
}

static void init_subtables() {
    const LootTableContext *subtable_ctx__0 = init_reward_rare_1_21_1();
    merge_item_lists(&context, subtable_ctx__0, 1);
    merge_loot_pools(&context, subtable_ctx__0, 1, 1);
    context.subtable_pool_offset[0] = context.pool_count;
    context.subtable_pool_count[0] = subtable_ctx__0->pool_count;
    context.subtable_count++;

    const LootTableContext *subtable_ctx__1 = init_reward_common_1_21_1();
    merge_item_lists(&context, subtable_ctx__1, 0);
    merge_loot_pools(&context, subtable_ctx__1, 0, 1);
    context.subtable_pool_offset[1] = context.subtable_pool_offset[0] + context.subtable_pool_count[0];
    context.subtable_pool_count[1] = subtable_ctx__1->pool_count;
    context.subtable_count++;

    const LootTableContext *subtable_ctx__2 = init_reward_unique_1_21_1();
    merge_item_lists(&context, subtable_ctx__2, 0);
    merge_loot_pools(&context, subtable_ctx__2, 0, 1);
    context.subtable_pool_offset[2] = context.subtable_pool_offset[1] + context.subtable_pool_count[1];
    context.subtable_pool_count[2] = subtable_ctx__2->pool_count;
    context.subtable_count++;
}

LootTableContext* init_reward_1_21_1() {
    if (!initialised) {
        create_loot_functions();
        init_subtables();
        initialised = 1;
    }
    return &context;
}
