// this file is automatically generated, do not edit!
#ifndef REWARD_1_21_1_H
#define REWARD_1_21_1_H

#include "../../../loot_table_context.h"

LootTableContext* init_reward_1_21_1();

#endif //REWARD_1_21_1_H
