// this file is automatically generated, do not edit!
#include "reward_ominous_common_1_21_1.h"

#include "../../../../biomes.h"

#include "../../../items.h"
#include "../../../loot_table_context.h"
#include "../../../loot_table_parser.h"

static int initialised = 0;

static char* item_names[5] = {"minecraft:emerald", "minecraft:wind_charge", "minecraft:tipped_arrow", "minecraft:diamond", "minecraft:ominous_bottle"};
static int global_item_ids[5] = {ITEM_EMERALD, ITEM_WIND_CHARGE, ITEM_TIPPED_ARROW, ITEM_DIAMOND, ITEM_OMINOUS_BOTTLE};

static LootItemCondition conditions__0[0];
static int precomputed_loot__0[15] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4};
static int entry_to_item__0[5] = {0, 1, 2, 3, 4};
static int entry_functions_count__0[5] = {1, 1, 2, 1, 2};
static int entry_functions_index__0[5] = {0, 1, 2, 4, 5};
static LootFunction loot_functions__0[7];
static const LootPool reward_ominous_common_1_21_1__0 = {
    .condition_count = 0,
    .conditions = conditions__0,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 5,
    .total_weight = 15,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {reward_ominous_common_1_21_1__0};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 5,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_set_count(&(loot_pool__0->loot_functions[0]), 4, 10);
    create_set_count(&(loot_pool__0->loot_functions[1]), 8, 12);
    create_set_count(&(loot_pool__0->loot_functions[2]), 4, 12);
    create_set_potion(&(loot_pool__0->loot_functions[3]), get_potion_from_name("minecraft:strong_slowness"));
    create_set_count(&(loot_pool__0->loot_functions[4]), 2, 3);
    create_set_count(&(loot_pool__0->loot_functions[5]), 1, 1);
    create_skip_calls(&(loot_pool__0->loot_functions[6]), 1);
}

LootTableContext* init_reward_ominous_common_1_21_1() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
