// this file is automatically generated, do not edit!
#ifndef REWARD_OMINOUS_UNIQUE_1_21_1_H
#define REWARD_OMINOUS_UNIQUE_1_21_1_H

#include "../../../loot_table_context.h"

LootTableContext* init_reward_ominous_unique_1_21_1();

#endif //REWARD_OMINOUS_UNIQUE_1_21_1_H
