// this file is automatically generated, do not edit!
#include "reward_ominous_rare_1_21_1.h"

#include "../../../../biomes.h"

#include "../../../items.h"
#include "../../../loot_table_context.h"
#include "../../../loot_table_parser.h"

static int initialised = 0;

static char* item_names[10] = {"minecraft:emerald_block", "minecraft:iron_block", "minecraft:crossbow", "minecraft:golden_apple", "minecraft:diamond_axe", "minecraft:diamond_chestplate", "minecraft:book", "minecraft:book", "minecraft:book", "minecraft:diamond_block"};
static int global_item_ids[10] = {ITEM_EMERALD_BLOCK, ITEM_IRON_BLOCK, ITEM_CROSSBOW, ITEM_GOLDEN_APPLE, ITEM_DIAMOND_AXE, ITEM_DIAMOND_CHESTPLATE, ITEM_BOOK, ITEM_BOOK, ITEM_BOOK, ITEM_DIAMOND_BLOCK};

static LootItemCondition conditions__0[0];
static int precomputed_loot__0[29] = {0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 7, 8, 8, 9};
static int entry_to_item__0[10] = {0, 1, 2, 3, 4, 5, 6, 6, 6, 9};
static int entry_functions_count__0[10] = {0, 0, 1, 0, 1, 1, 1, 1, 1, 0};
static int entry_functions_index__0[10] = {0, 0, 0, 1, 1, 2, 3, 4, 5, 6};
static LootFunction loot_functions__0[6];
static const LootPool reward_ominous_rare_1_21_1__0 = {
    .condition_count = 0,
    .conditions = conditions__0,
    .min_rolls = 1,
    .max_rolls = 1,
    .roll_count_function = roll_count_constant,
    .entry_count = 10,
    .total_weight = 29,
    .precomputed_loot = precomputed_loot__0,
    .entry_to_item = entry_to_item__0,
    .entry_functions_count = entry_functions_count__0,
    .entry_functions_index = entry_functions_index__0,
    .loot_functions = loot_functions__0,
};

static LootPool loot_pools[1] = {reward_ominous_rare_1_21_1__0};
static LootTableContext context = {
    .version = MC_1_21_1,
    .item_count = 10,
    .item_names = item_names,
    .global_item_ids = global_item_ids,
    .unresolved_subtable_count = 0,
    .subtable_count = 0,
    .subtable_pool_offset = NULL,
    .subtable_pool_count = NULL,
    .pool_count = 1,
    .loot_pools = loot_pools,
};

static void create_loot_functions() {
    LootPool* loot_pool__0 = &(context.loot_pools[0]);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[0]), MC_1_21_1, "minecraft:crossbow", get_item_type("minecraft:crossbow"), 5, 20, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[1]), MC_1_21_1, "minecraft:diamond_axe", get_item_type("minecraft:diamond_axe"), 10, 20, "#minecraft:on_random_loot", 1);
    create_enchant_with_levels_tag(&(loot_pool__0->loot_functions[2]), MC_1_21_1, "minecraft:diamond_chestplate", get_item_type("minecraft:diamond_chestplate"), 10, 20, "#minecraft:on_random_loot", 1);
    create_enchant_randomly_list(&(loot_pool__0->loot_functions[3]), (Enchantment[]){get_enchantment_from_name("minecraft:knockback"), get_enchantment_from_name("minecraft:punch"), get_enchantment_from_name("minecraft:smite"), get_enchantment_from_name("minecraft:looting"), get_enchantment_from_name("minecraft:multishot")}, 5);
    create_enchant_randomly_list(&(loot_pool__0->loot_functions[4]), (Enchantment[]){get_enchantment_from_name("minecraft:breach"), get_enchantment_from_name("minecraft:density")}, 2);
    create_set_enchantments(&(loot_pool__0->loot_functions[5]), (Enchantment[]){get_enchantment_from_name("minecraft:wind_burst")}, (int[]){1}, 1);
}

LootTableContext* init_reward_ominous_rare_1_21_1() {
    if (!initialised) {
        create_loot_functions();
        initialised = 1;
    }
    return &context;
}
