// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OreConfig {
 *     int32_t index;
 *     int32_t step;
 *     int32_t size;
 *     int32_t repeatCount;
 *     int (*heightProvider)(RandomSource, int, int, int);
 *     int32_t h1;
 *     int32_t h2;
 *     int32_t h3;
 *     uint32_t oreType;
 *     uint32_t oreBlock;
 *     int8_t dim;
 *     uint8_t numReplaceBlocks;
 *     const uint32_t *replaceBlocks;
 *     float discardChanceOnAirExposure;
 * }
 * }
 */
public class OreConfig {

    OreConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("index"),
        Cubiomes.C_INT.withName("step"),
        Cubiomes.C_INT.withName("size"),
        Cubiomes.C_INT.withName("repeatCount"),
        Cubiomes.C_POINTER.withName("heightProvider"),
        Cubiomes.C_INT.withName("h1"),
        Cubiomes.C_INT.withName("h2"),
        Cubiomes.C_INT.withName("h3"),
        Cubiomes.C_INT.withName("oreType"),
        Cubiomes.C_INT.withName("oreBlock"),
        Cubiomes.C_CHAR.withName("dim"),
        Cubiomes.C_CHAR.withName("numReplaceBlocks"),
        MemoryLayout.paddingLayout(2),
        Cubiomes.C_POINTER.withName("replaceBlocks"),
        Cubiomes.C_FLOAT.withName("discardChanceOnAirExposure"),
        MemoryLayout.paddingLayout(4)
    ).withName("OreConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt index$LAYOUT = (OfInt)$LAYOUT.select(groupElement("index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t index
     * }
     */
    public static final OfInt index$layout() {
        return index$LAYOUT;
    }

    private static final long index$OFFSET = $LAYOUT.byteOffset(groupElement("index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t index
     * }
     */
    public static final long index$offset() {
        return index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t index
     * }
     */
    public static int index(MemorySegment struct) {
        return struct.get(index$LAYOUT, index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t index
     * }
     */
    public static void index(MemorySegment struct, int fieldValue) {
        struct.set(index$LAYOUT, index$OFFSET, fieldValue);
    }

    private static final OfInt step$LAYOUT = (OfInt)$LAYOUT.select(groupElement("step"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t step
     * }
     */
    public static final OfInt step$layout() {
        return step$LAYOUT;
    }

    private static final long step$OFFSET = $LAYOUT.byteOffset(groupElement("step"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t step
     * }
     */
    public static final long step$offset() {
        return step$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t step
     * }
     */
    public static int step(MemorySegment struct) {
        return struct.get(step$LAYOUT, step$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t step
     * }
     */
    public static void step(MemorySegment struct, int fieldValue) {
        struct.set(step$LAYOUT, step$OFFSET, fieldValue);
    }

    private static final OfInt size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t size
     * }
     */
    public static final OfInt size$layout() {
        return size$LAYOUT;
    }

    private static final long size$OFFSET = $LAYOUT.byteOffset(groupElement("size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t size
     * }
     */
    public static final long size$offset() {
        return size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t size
     * }
     */
    public static int size(MemorySegment struct) {
        return struct.get(size$LAYOUT, size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t size
     * }
     */
    public static void size(MemorySegment struct, int fieldValue) {
        struct.set(size$LAYOUT, size$OFFSET, fieldValue);
    }

    private static final OfInt repeatCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("repeatCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t repeatCount
     * }
     */
    public static final OfInt repeatCount$layout() {
        return repeatCount$LAYOUT;
    }

    private static final long repeatCount$OFFSET = $LAYOUT.byteOffset(groupElement("repeatCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t repeatCount
     * }
     */
    public static final long repeatCount$offset() {
        return repeatCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t repeatCount
     * }
     */
    public static int repeatCount(MemorySegment struct) {
        return struct.get(repeatCount$LAYOUT, repeatCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t repeatCount
     * }
     */
    public static void repeatCount(MemorySegment struct, int fieldValue) {
        struct.set(repeatCount$LAYOUT, repeatCount$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*heightProvider)(RandomSource, int, int, int)
     * }
     */
    public static class heightProvider {

        heightProvider() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2, int _x3);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_INT,
            RandomSource.layout(),
            Cubiomes.C_INT,
            Cubiomes.C_INT,
            Cubiomes.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(heightProvider.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(heightProvider.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, int _x2, int _x3) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout heightProvider$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("heightProvider"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*heightProvider)(RandomSource, int, int, int)
     * }
     */
    public static final AddressLayout heightProvider$layout() {
        return heightProvider$LAYOUT;
    }

    private static final long heightProvider$OFFSET = $LAYOUT.byteOffset(groupElement("heightProvider"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*heightProvider)(RandomSource, int, int, int)
     * }
     */
    public static final long heightProvider$offset() {
        return heightProvider$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*heightProvider)(RandomSource, int, int, int)
     * }
     */
    public static MemorySegment heightProvider(MemorySegment struct) {
        return struct.get(heightProvider$LAYOUT, heightProvider$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*heightProvider)(RandomSource, int, int, int)
     * }
     */
    public static void heightProvider(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(heightProvider$LAYOUT, heightProvider$OFFSET, fieldValue);
    }

    private static final OfInt h1$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t h1
     * }
     */
    public static final OfInt h1$layout() {
        return h1$LAYOUT;
    }

    private static final long h1$OFFSET = $LAYOUT.byteOffset(groupElement("h1"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t h1
     * }
     */
    public static final long h1$offset() {
        return h1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t h1
     * }
     */
    public static int h1(MemorySegment struct) {
        return struct.get(h1$LAYOUT, h1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t h1
     * }
     */
    public static void h1(MemorySegment struct, int fieldValue) {
        struct.set(h1$LAYOUT, h1$OFFSET, fieldValue);
    }

    private static final OfInt h2$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t h2
     * }
     */
    public static final OfInt h2$layout() {
        return h2$LAYOUT;
    }

    private static final long h2$OFFSET = $LAYOUT.byteOffset(groupElement("h2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t h2
     * }
     */
    public static final long h2$offset() {
        return h2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t h2
     * }
     */
    public static int h2(MemorySegment struct) {
        return struct.get(h2$LAYOUT, h2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t h2
     * }
     */
    public static void h2(MemorySegment struct, int fieldValue) {
        struct.set(h2$LAYOUT, h2$OFFSET, fieldValue);
    }

    private static final OfInt h3$LAYOUT = (OfInt)$LAYOUT.select(groupElement("h3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t h3
     * }
     */
    public static final OfInt h3$layout() {
        return h3$LAYOUT;
    }

    private static final long h3$OFFSET = $LAYOUT.byteOffset(groupElement("h3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t h3
     * }
     */
    public static final long h3$offset() {
        return h3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t h3
     * }
     */
    public static int h3(MemorySegment struct) {
        return struct.get(h3$LAYOUT, h3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t h3
     * }
     */
    public static void h3(MemorySegment struct, int fieldValue) {
        struct.set(h3$LAYOUT, h3$OFFSET, fieldValue);
    }

    private static final OfInt oreType$LAYOUT = (OfInt)$LAYOUT.select(groupElement("oreType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t oreType
     * }
     */
    public static final OfInt oreType$layout() {
        return oreType$LAYOUT;
    }

    private static final long oreType$OFFSET = $LAYOUT.byteOffset(groupElement("oreType"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t oreType
     * }
     */
    public static final long oreType$offset() {
        return oreType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t oreType
     * }
     */
    public static int oreType(MemorySegment struct) {
        return struct.get(oreType$LAYOUT, oreType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t oreType
     * }
     */
    public static void oreType(MemorySegment struct, int fieldValue) {
        struct.set(oreType$LAYOUT, oreType$OFFSET, fieldValue);
    }

    private static final OfInt oreBlock$LAYOUT = (OfInt)$LAYOUT.select(groupElement("oreBlock"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static final OfInt oreBlock$layout() {
        return oreBlock$LAYOUT;
    }

    private static final long oreBlock$OFFSET = $LAYOUT.byteOffset(groupElement("oreBlock"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static final long oreBlock$offset() {
        return oreBlock$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static int oreBlock(MemorySegment struct) {
        return struct.get(oreBlock$LAYOUT, oreBlock$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static void oreBlock(MemorySegment struct, int fieldValue) {
        struct.set(oreBlock$LAYOUT, oreBlock$OFFSET, fieldValue);
    }

    private static final OfByte dim$LAYOUT = (OfByte)$LAYOUT.select(groupElement("dim"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int8_t dim
     * }
     */
    public static final OfByte dim$layout() {
        return dim$LAYOUT;
    }

    private static final long dim$OFFSET = $LAYOUT.byteOffset(groupElement("dim"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int8_t dim
     * }
     */
    public static final long dim$offset() {
        return dim$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int8_t dim
     * }
     */
    public static byte dim(MemorySegment struct) {
        return struct.get(dim$LAYOUT, dim$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int8_t dim
     * }
     */
    public static void dim(MemorySegment struct, byte fieldValue) {
        struct.set(dim$LAYOUT, dim$OFFSET, fieldValue);
    }

    private static final OfByte numReplaceBlocks$LAYOUT = (OfByte)$LAYOUT.select(groupElement("numReplaceBlocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t numReplaceBlocks
     * }
     */
    public static final OfByte numReplaceBlocks$layout() {
        return numReplaceBlocks$LAYOUT;
    }

    private static final long numReplaceBlocks$OFFSET = $LAYOUT.byteOffset(groupElement("numReplaceBlocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t numReplaceBlocks
     * }
     */
    public static final long numReplaceBlocks$offset() {
        return numReplaceBlocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t numReplaceBlocks
     * }
     */
    public static byte numReplaceBlocks(MemorySegment struct) {
        return struct.get(numReplaceBlocks$LAYOUT, numReplaceBlocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t numReplaceBlocks
     * }
     */
    public static void numReplaceBlocks(MemorySegment struct, byte fieldValue) {
        struct.set(numReplaceBlocks$LAYOUT, numReplaceBlocks$OFFSET, fieldValue);
    }

    private static final AddressLayout replaceBlocks$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("replaceBlocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const uint32_t *replaceBlocks
     * }
     */
    public static final AddressLayout replaceBlocks$layout() {
        return replaceBlocks$LAYOUT;
    }

    private static final long replaceBlocks$OFFSET = $LAYOUT.byteOffset(groupElement("replaceBlocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const uint32_t *replaceBlocks
     * }
     */
    public static final long replaceBlocks$offset() {
        return replaceBlocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const uint32_t *replaceBlocks
     * }
     */
    public static MemorySegment replaceBlocks(MemorySegment struct) {
        return struct.get(replaceBlocks$LAYOUT, replaceBlocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const uint32_t *replaceBlocks
     * }
     */
    public static void replaceBlocks(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(replaceBlocks$LAYOUT, replaceBlocks$OFFSET, fieldValue);
    }

    private static final OfFloat discardChanceOnAirExposure$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("discardChanceOnAirExposure"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float discardChanceOnAirExposure
     * }
     */
    public static final OfFloat discardChanceOnAirExposure$layout() {
        return discardChanceOnAirExposure$LAYOUT;
    }

    private static final long discardChanceOnAirExposure$OFFSET = $LAYOUT.byteOffset(groupElement("discardChanceOnAirExposure"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float discardChanceOnAirExposure
     * }
     */
    public static final long discardChanceOnAirExposure$offset() {
        return discardChanceOnAirExposure$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float discardChanceOnAirExposure
     * }
     */
    public static float discardChanceOnAirExposure(MemorySegment struct) {
        return struct.get(discardChanceOnAirExposure$LAYOUT, discardChanceOnAirExposure$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float discardChanceOnAirExposure
     * }
     */
    public static void discardChanceOnAirExposure(MemorySegment struct, float fieldValue) {
        struct.set(discardChanceOnAirExposure$LAYOUT, discardChanceOnAirExposure$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

