// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OreVeinParameters {
 *     PerlinNoise oct[8];
 *     DoublePerlinNoise oreVeininess;
 *     DoublePerlinNoise oreVeinA;
 *     DoublePerlinNoise oreVeinB;
 *     DoublePerlinNoise oreGap;
 *     Xoroshiro posRandom;
 * }
 * }
 */
public class OreVeinParameters {

    OreVeinParameters() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, PerlinNoise.layout()).withName("oct"),
        DoublePerlinNoise.layout().withName("oreVeininess"),
        DoublePerlinNoise.layout().withName("oreVeinA"),
        DoublePerlinNoise.layout().withName("oreVeinB"),
        DoublePerlinNoise.layout().withName("oreGap"),
        Xoroshiro.layout().withName("posRandom")
    ).withName("OreVeinParameters");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout oct$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("oct"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static final SequenceLayout oct$layout() {
        return oct$LAYOUT;
    }

    private static final long oct$OFFSET = $LAYOUT.byteOffset(groupElement("oct"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static final long oct$offset() {
        return oct$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static MemorySegment oct(MemorySegment struct) {
        return struct.asSlice(oct$OFFSET, oct$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static void oct(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oct$OFFSET, oct$LAYOUT.byteSize());
    }

    private static long[] oct$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static long[] oct$dimensions() {
        return oct$DIMS;
    }
    private static final MethodHandle oct$ELEM_HANDLE = oct$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static MemorySegment oct(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)oct$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * PerlinNoise oct[8]
     * }
     */
    public static void oct(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, oct(struct, index0), 0L, PerlinNoise.layout().byteSize());
    }

    private static final GroupLayout oreVeininess$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("oreVeininess"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeininess
     * }
     */
    public static final GroupLayout oreVeininess$layout() {
        return oreVeininess$LAYOUT;
    }

    private static final long oreVeininess$OFFSET = $LAYOUT.byteOffset(groupElement("oreVeininess"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeininess
     * }
     */
    public static final long oreVeininess$offset() {
        return oreVeininess$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeininess
     * }
     */
    public static MemorySegment oreVeininess(MemorySegment struct) {
        return struct.asSlice(oreVeininess$OFFSET, oreVeininess$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeininess
     * }
     */
    public static void oreVeininess(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oreVeininess$OFFSET, oreVeininess$LAYOUT.byteSize());
    }

    private static final GroupLayout oreVeinA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("oreVeinA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinA
     * }
     */
    public static final GroupLayout oreVeinA$layout() {
        return oreVeinA$LAYOUT;
    }

    private static final long oreVeinA$OFFSET = $LAYOUT.byteOffset(groupElement("oreVeinA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinA
     * }
     */
    public static final long oreVeinA$offset() {
        return oreVeinA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinA
     * }
     */
    public static MemorySegment oreVeinA(MemorySegment struct) {
        return struct.asSlice(oreVeinA$OFFSET, oreVeinA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinA
     * }
     */
    public static void oreVeinA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oreVeinA$OFFSET, oreVeinA$LAYOUT.byteSize());
    }

    private static final GroupLayout oreVeinB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("oreVeinB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinB
     * }
     */
    public static final GroupLayout oreVeinB$layout() {
        return oreVeinB$LAYOUT;
    }

    private static final long oreVeinB$OFFSET = $LAYOUT.byteOffset(groupElement("oreVeinB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinB
     * }
     */
    public static final long oreVeinB$offset() {
        return oreVeinB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinB
     * }
     */
    public static MemorySegment oreVeinB(MemorySegment struct) {
        return struct.asSlice(oreVeinB$OFFSET, oreVeinB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreVeinB
     * }
     */
    public static void oreVeinB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oreVeinB$OFFSET, oreVeinB$LAYOUT.byteSize());
    }

    private static final GroupLayout oreGap$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("oreGap"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreGap
     * }
     */
    public static final GroupLayout oreGap$layout() {
        return oreGap$LAYOUT;
    }

    private static final long oreGap$OFFSET = $LAYOUT.byteOffset(groupElement("oreGap"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreGap
     * }
     */
    public static final long oreGap$offset() {
        return oreGap$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreGap
     * }
     */
    public static MemorySegment oreGap(MemorySegment struct) {
        return struct.asSlice(oreGap$OFFSET, oreGap$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * DoublePerlinNoise oreGap
     * }
     */
    public static void oreGap(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, oreGap$OFFSET, oreGap$LAYOUT.byteSize());
    }

    private static final GroupLayout posRandom$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("posRandom"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Xoroshiro posRandom
     * }
     */
    public static final GroupLayout posRandom$layout() {
        return posRandom$LAYOUT;
    }

    private static final long posRandom$OFFSET = $LAYOUT.byteOffset(groupElement("posRandom"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Xoroshiro posRandom
     * }
     */
    public static final long posRandom$offset() {
        return posRandom$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Xoroshiro posRandom
     * }
     */
    public static MemorySegment posRandom(MemorySegment struct) {
        return struct.asSlice(posRandom$OFFSET, posRandom$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Xoroshiro posRandom
     * }
     */
    public static void posRandom(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, posRandom$OFFSET, posRandom$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

