// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RandomSource {
 *     void *state;
 *     void (*setSeed)(void *, uint64_t);
 *     uint64_t (*nextLong)(void *);
 *     int (*nextInt)(void *, int);
 *     float (*nextFloat)(void *);
 *     double (*nextDouble)(void *);
 *     int (*nextIntBetween)(void *, int, int);
 * }
 * }
 */
public class RandomSource {

    RandomSource() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_POINTER.withName("state"),
        Cubiomes.C_POINTER.withName("setSeed"),
        Cubiomes.C_POINTER.withName("nextLong"),
        Cubiomes.C_POINTER.withName("nextInt"),
        Cubiomes.C_POINTER.withName("nextFloat"),
        Cubiomes.C_POINTER.withName("nextDouble"),
        Cubiomes.C_POINTER.withName("nextIntBetween")
    ).withName("RandomSource");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout state$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static final AddressLayout state$layout() {
        return state$LAYOUT;
    }

    private static final long state$OFFSET = $LAYOUT.byteOffset(groupElement("state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static final long state$offset() {
        return state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static MemorySegment state(MemorySegment struct) {
        return struct.get(state$LAYOUT, state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *state
     * }
     */
    public static void state(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(state$LAYOUT, state$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*setSeed)(void *, uint64_t)
     * }
     */
    public static class setSeed {

        setSeed() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0, long _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Cubiomes.C_POINTER,
            Cubiomes.C_LONG
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(setSeed.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(setSeed.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0, long _x1) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout setSeed$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("setSeed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*setSeed)(void *, uint64_t)
     * }
     */
    public static final AddressLayout setSeed$layout() {
        return setSeed$LAYOUT;
    }

    private static final long setSeed$OFFSET = $LAYOUT.byteOffset(groupElement("setSeed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*setSeed)(void *, uint64_t)
     * }
     */
    public static final long setSeed$offset() {
        return setSeed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*setSeed)(void *, uint64_t)
     * }
     */
    public static MemorySegment setSeed(MemorySegment struct) {
        return struct.get(setSeed$LAYOUT, setSeed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*setSeed)(void *, uint64_t)
     * }
     */
    public static void setSeed(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(setSeed$LAYOUT, setSeed$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * uint64_t (*nextLong)(void *)
     * }
     */
    public static class nextLong {

        nextLong() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            long apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_LONG,
            Cubiomes.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(nextLong.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(nextLong.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static long invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (long) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout nextLong$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextLong"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t (*nextLong)(void *)
     * }
     */
    public static final AddressLayout nextLong$layout() {
        return nextLong$LAYOUT;
    }

    private static final long nextLong$OFFSET = $LAYOUT.byteOffset(groupElement("nextLong"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t (*nextLong)(void *)
     * }
     */
    public static final long nextLong$offset() {
        return nextLong$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t (*nextLong)(void *)
     * }
     */
    public static MemorySegment nextLong(MemorySegment struct) {
        return struct.get(nextLong$LAYOUT, nextLong$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t (*nextLong)(void *)
     * }
     */
    public static void nextLong(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextLong$LAYOUT, nextLong$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*nextInt)(void *, int)
     * }
     */
    public static class nextInt {

        nextInt() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_INT,
            Cubiomes.C_POINTER,
            Cubiomes.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(nextInt.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(nextInt.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout nextInt$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextInt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*nextInt)(void *, int)
     * }
     */
    public static final AddressLayout nextInt$layout() {
        return nextInt$LAYOUT;
    }

    private static final long nextInt$OFFSET = $LAYOUT.byteOffset(groupElement("nextInt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*nextInt)(void *, int)
     * }
     */
    public static final long nextInt$offset() {
        return nextInt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*nextInt)(void *, int)
     * }
     */
    public static MemorySegment nextInt(MemorySegment struct) {
        return struct.get(nextInt$LAYOUT, nextInt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*nextInt)(void *, int)
     * }
     */
    public static void nextInt(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextInt$LAYOUT, nextInt$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * float (*nextFloat)(void *)
     * }
     */
    public static class nextFloat {

        nextFloat() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            float apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_FLOAT,
            Cubiomes.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(nextFloat.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(nextFloat.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static float invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (float) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout nextFloat$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextFloat"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float (*nextFloat)(void *)
     * }
     */
    public static final AddressLayout nextFloat$layout() {
        return nextFloat$LAYOUT;
    }

    private static final long nextFloat$OFFSET = $LAYOUT.byteOffset(groupElement("nextFloat"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float (*nextFloat)(void *)
     * }
     */
    public static final long nextFloat$offset() {
        return nextFloat$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float (*nextFloat)(void *)
     * }
     */
    public static MemorySegment nextFloat(MemorySegment struct) {
        return struct.get(nextFloat$LAYOUT, nextFloat$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float (*nextFloat)(void *)
     * }
     */
    public static void nextFloat(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextFloat$LAYOUT, nextFloat$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * double (*nextDouble)(void *)
     * }
     */
    public static class nextDouble {

        nextDouble() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            double apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_DOUBLE,
            Cubiomes.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(nextDouble.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(nextDouble.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static double invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (double) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout nextDouble$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextDouble"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double (*nextDouble)(void *)
     * }
     */
    public static final AddressLayout nextDouble$layout() {
        return nextDouble$LAYOUT;
    }

    private static final long nextDouble$OFFSET = $LAYOUT.byteOffset(groupElement("nextDouble"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double (*nextDouble)(void *)
     * }
     */
    public static final long nextDouble$offset() {
        return nextDouble$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double (*nextDouble)(void *)
     * }
     */
    public static MemorySegment nextDouble(MemorySegment struct) {
        return struct.get(nextDouble$LAYOUT, nextDouble$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double (*nextDouble)(void *)
     * }
     */
    public static void nextDouble(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextDouble$LAYOUT, nextDouble$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*nextIntBetween)(void *, int, int)
     * }
     */
    public static class nextIntBetween {

        nextIntBetween() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, int _x1, int _x2);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Cubiomes.C_INT,
            Cubiomes.C_POINTER,
            Cubiomes.C_INT,
            Cubiomes.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Cubiomes.upcallHandle(nextIntBetween.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(nextIntBetween.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, int _x1, int _x2) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout nextIntBetween$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("nextIntBetween"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*nextIntBetween)(void *, int, int)
     * }
     */
    public static final AddressLayout nextIntBetween$layout() {
        return nextIntBetween$LAYOUT;
    }

    private static final long nextIntBetween$OFFSET = $LAYOUT.byteOffset(groupElement("nextIntBetween"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*nextIntBetween)(void *, int, int)
     * }
     */
    public static final long nextIntBetween$offset() {
        return nextIntBetween$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*nextIntBetween)(void *, int, int)
     * }
     */
    public static MemorySegment nextIntBetween(MemorySegment struct) {
        return struct.get(nextIntBetween$LAYOUT, nextIntBetween$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*nextIntBetween)(void *, int, int)
     * }
     */
    public static void nextIntBetween(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(nextIntBetween$LAYOUT, nextIntBetween$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

