// Generated by jextract

package com.github.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct StructureSaltConfig {
 *     int32_t generationStep;
 *     int32_t decoratorIndex;
 * }
 * }
 */
public class StructureSaltConfig {

    StructureSaltConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("generationStep"),
        Cubiomes.C_INT.withName("decoratorIndex")
    ).withName("StructureSaltConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt generationStep$LAYOUT = (OfInt)$LAYOUT.select(groupElement("generationStep"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t generationStep
     * }
     */
    public static final OfInt generationStep$layout() {
        return generationStep$LAYOUT;
    }

    private static final long generationStep$OFFSET = $LAYOUT.byteOffset(groupElement("generationStep"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t generationStep
     * }
     */
    public static final long generationStep$offset() {
        return generationStep$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t generationStep
     * }
     */
    public static int generationStep(MemorySegment struct) {
        return struct.get(generationStep$LAYOUT, generationStep$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t generationStep
     * }
     */
    public static void generationStep(MemorySegment struct, int fieldValue) {
        struct.set(generationStep$LAYOUT, generationStep$OFFSET, fieldValue);
    }

    private static final OfInt decoratorIndex$LAYOUT = (OfInt)$LAYOUT.select(groupElement("decoratorIndex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t decoratorIndex
     * }
     */
    public static final OfInt decoratorIndex$layout() {
        return decoratorIndex$LAYOUT;
    }

    private static final long decoratorIndex$OFFSET = $LAYOUT.byteOffset(groupElement("decoratorIndex"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t decoratorIndex
     * }
     */
    public static final long decoratorIndex$offset() {
        return decoratorIndex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t decoratorIndex
     * }
     */
    public static int decoratorIndex(MemorySegment struct) {
        return struct.get(decoratorIndex$LAYOUT, decoratorIndex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t decoratorIndex
     * }
     */
    public static void decoratorIndex(MemorySegment struct, int fieldValue) {
        struct.set(decoratorIndex$LAYOUT, decoratorIndex$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

