// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Cubiomes extends Cubiomes_1 {

    Cubiomes() {
        // Should not be called directly
    }
    private static final long LAYER_INIT_SHA = -1L;
    /**
     * {@snippet lang=c :
     * #define LAYER_INIT_SHA -1
     * }
     */
    public static long LAYER_INIT_SHA() {
        return LAYER_INIT_SHA;
    }
    private static final long MASK48 = 281474976710655L;
    /**
     * {@snippet lang=c :
     * #define MASK48 281474976710655
     * }
     */
    public static long MASK48() {
        return MASK48;
    }
}

