// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef double (*interpFunc)(double, double, double, double, double, double, double, double, double, double, double)
 * }
 */
public final class interpFunc {

    private interpFunc() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        double apply(double dx, double dy, double dz, double v000, double v100, double v010, double v110, double v001, double v101, double v011, double v111);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE,
        Cubiomes.C_DOUBLE
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Cubiomes.upcallHandle(interpFunc.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(interpFunc.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static double invoke(MemorySegment funcPtr, double dx, double dy, double dz, double v000, double v100, double v010, double v110, double v001, double v101, double v011, double v111) {
        try {
            return (double) DOWN$MH.invokeExact(funcPtr, dx, dy, dz, v000, v100, v010, v110, v001, v101, v011, v111);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

