// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ItemStack {
 *     int item;
 *     int count;
 *     int enchantment_count;
 *     EnchantInstance enchantments[16];
 *     MobEffectInstance mob_effect;
 * }
 * }
 */
public class ItemStack {

    ItemStack() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("item"),
        Cubiomes.C_INT.withName("count"),
        Cubiomes.C_INT.withName("enchantment_count"),
        MemoryLayout.sequenceLayout(16, EnchantInstance.layout()).withName("enchantments"),
        MobEffectInstance.layout().withName("mob_effect")
    ).withName("ItemStack");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt item$LAYOUT = (OfInt)$LAYOUT.select(groupElement("item"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int item
     * }
     */
    public static final OfInt item$layout() {
        return item$LAYOUT;
    }

    private static final long item$OFFSET = $LAYOUT.byteOffset(groupElement("item"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int item
     * }
     */
    public static final long item$offset() {
        return item$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int item
     * }
     */
    public static int item(MemorySegment struct) {
        return struct.get(item$LAYOUT, item$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int item
     * }
     */
    public static void item(MemorySegment struct, int fieldValue) {
        struct.set(item$LAYOUT, item$OFFSET, fieldValue);
    }

    private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static final OfInt count$layout() {
        return count$LAYOUT;
    }

    private static final long count$OFFSET = $LAYOUT.byteOffset(groupElement("count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static final long count$offset() {
        return count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static int count(MemorySegment struct) {
        return struct.get(count$LAYOUT, count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int count
     * }
     */
    public static void count(MemorySegment struct, int fieldValue) {
        struct.set(count$LAYOUT, count$OFFSET, fieldValue);
    }

    private static final OfInt enchantment_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("enchantment_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int enchantment_count
     * }
     */
    public static final OfInt enchantment_count$layout() {
        return enchantment_count$LAYOUT;
    }

    private static final long enchantment_count$OFFSET = $LAYOUT.byteOffset(groupElement("enchantment_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int enchantment_count
     * }
     */
    public static final long enchantment_count$offset() {
        return enchantment_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int enchantment_count
     * }
     */
    public static int enchantment_count(MemorySegment struct) {
        return struct.get(enchantment_count$LAYOUT, enchantment_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int enchantment_count
     * }
     */
    public static void enchantment_count(MemorySegment struct, int fieldValue) {
        struct.set(enchantment_count$LAYOUT, enchantment_count$OFFSET, fieldValue);
    }

    private static final SequenceLayout enchantments$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("enchantments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static final SequenceLayout enchantments$layout() {
        return enchantments$LAYOUT;
    }

    private static final long enchantments$OFFSET = $LAYOUT.byteOffset(groupElement("enchantments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static final long enchantments$offset() {
        return enchantments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static MemorySegment enchantments(MemorySegment struct) {
        return struct.asSlice(enchantments$OFFSET, enchantments$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static void enchantments(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, enchantments$OFFSET, enchantments$LAYOUT.byteSize());
    }

    private static long[] enchantments$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static long[] enchantments$dimensions() {
        return enchantments$DIMS;
    }
    private static final MethodHandle enchantments$ELEM_HANDLE = enchantments$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static MemorySegment enchantments(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)enchantments$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * EnchantInstance enchantments[16]
     * }
     */
    public static void enchantments(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, enchantments(struct, index0), 0L, EnchantInstance.layout().byteSize());
    }

    private static final GroupLayout mob_effect$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("mob_effect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MobEffectInstance mob_effect
     * }
     */
    public static final GroupLayout mob_effect$layout() {
        return mob_effect$LAYOUT;
    }

    private static final long mob_effect$OFFSET = $LAYOUT.byteOffset(groupElement("mob_effect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MobEffectInstance mob_effect
     * }
     */
    public static final long mob_effect$offset() {
        return mob_effect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MobEffectInstance mob_effect
     * }
     */
    public static MemorySegment mob_effect(MemorySegment struct) {
        return struct.asSlice(mob_effect$OFFSET, mob_effect$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MobEffectInstance mob_effect
     * }
     */
    public static void mob_effect(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, mob_effect$OFFSET, mob_effect$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

