// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct LootTableContext {
 *     int version;
 *     int item_count;
 *     char **item_names;
 *     int *global_item_ids;
 *     int pool_count;
 *     LootPool *loot_pools;
 *     int unresolved_subtable_count;
 *     char *unresolved_subtable_names[8];
 *     int subtable_count;
 *     int *subtable_pool_offset;
 *     int *subtable_pool_count;
 *     uint64_t prng_state;
 *     int generated_item_count;
 *     ItemStack generated_items[27];
 * }
 * }
 */
public class LootTableContext {

    LootTableContext() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("version"),
        Cubiomes.C_INT.withName("item_count"),
        Cubiomes.C_POINTER.withName("item_names"),
        Cubiomes.C_POINTER.withName("global_item_ids"),
        Cubiomes.C_INT.withName("pool_count"),
        MemoryLayout.paddingLayout(4),
        Cubiomes.C_POINTER.withName("loot_pools"),
        Cubiomes.C_INT.withName("unresolved_subtable_count"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.sequenceLayout(8, Cubiomes.C_POINTER).withName("unresolved_subtable_names"),
        Cubiomes.C_INT.withName("subtable_count"),
        MemoryLayout.paddingLayout(4),
        Cubiomes.C_POINTER.withName("subtable_pool_offset"),
        Cubiomes.C_POINTER.withName("subtable_pool_count"),
        Cubiomes.C_LONG.withName("prng_state"),
        Cubiomes.C_INT.withName("generated_item_count"),
        MemoryLayout.sequenceLayout(27, ItemStack.layout()).withName("generated_items")
    ).withName("LootTableContext");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfInt item_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("item_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int item_count
     * }
     */
    public static final OfInt item_count$layout() {
        return item_count$LAYOUT;
    }

    private static final long item_count$OFFSET = $LAYOUT.byteOffset(groupElement("item_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int item_count
     * }
     */
    public static final long item_count$offset() {
        return item_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int item_count
     * }
     */
    public static int item_count(MemorySegment struct) {
        return struct.get(item_count$LAYOUT, item_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int item_count
     * }
     */
    public static void item_count(MemorySegment struct, int fieldValue) {
        struct.set(item_count$LAYOUT, item_count$OFFSET, fieldValue);
    }

    private static final AddressLayout item_names$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("item_names"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **item_names
     * }
     */
    public static final AddressLayout item_names$layout() {
        return item_names$LAYOUT;
    }

    private static final long item_names$OFFSET = $LAYOUT.byteOffset(groupElement("item_names"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **item_names
     * }
     */
    public static final long item_names$offset() {
        return item_names$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **item_names
     * }
     */
    public static MemorySegment item_names(MemorySegment struct) {
        return struct.get(item_names$LAYOUT, item_names$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **item_names
     * }
     */
    public static void item_names(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(item_names$LAYOUT, item_names$OFFSET, fieldValue);
    }

    private static final AddressLayout global_item_ids$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("global_item_ids"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *global_item_ids
     * }
     */
    public static final AddressLayout global_item_ids$layout() {
        return global_item_ids$LAYOUT;
    }

    private static final long global_item_ids$OFFSET = $LAYOUT.byteOffset(groupElement("global_item_ids"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *global_item_ids
     * }
     */
    public static final long global_item_ids$offset() {
        return global_item_ids$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *global_item_ids
     * }
     */
    public static MemorySegment global_item_ids(MemorySegment struct) {
        return struct.get(global_item_ids$LAYOUT, global_item_ids$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *global_item_ids
     * }
     */
    public static void global_item_ids(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(global_item_ids$LAYOUT, global_item_ids$OFFSET, fieldValue);
    }

    private static final OfInt pool_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pool_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int pool_count
     * }
     */
    public static final OfInt pool_count$layout() {
        return pool_count$LAYOUT;
    }

    private static final long pool_count$OFFSET = $LAYOUT.byteOffset(groupElement("pool_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int pool_count
     * }
     */
    public static final long pool_count$offset() {
        return pool_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pool_count
     * }
     */
    public static int pool_count(MemorySegment struct) {
        return struct.get(pool_count$LAYOUT, pool_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pool_count
     * }
     */
    public static void pool_count(MemorySegment struct, int fieldValue) {
        struct.set(pool_count$LAYOUT, pool_count$OFFSET, fieldValue);
    }

    private static final AddressLayout loot_pools$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("loot_pools"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * LootPool *loot_pools
     * }
     */
    public static final AddressLayout loot_pools$layout() {
        return loot_pools$LAYOUT;
    }

    private static final long loot_pools$OFFSET = $LAYOUT.byteOffset(groupElement("loot_pools"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * LootPool *loot_pools
     * }
     */
    public static final long loot_pools$offset() {
        return loot_pools$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * LootPool *loot_pools
     * }
     */
    public static MemorySegment loot_pools(MemorySegment struct) {
        return struct.get(loot_pools$LAYOUT, loot_pools$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * LootPool *loot_pools
     * }
     */
    public static void loot_pools(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(loot_pools$LAYOUT, loot_pools$OFFSET, fieldValue);
    }

    private static final OfInt unresolved_subtable_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("unresolved_subtable_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int unresolved_subtable_count
     * }
     */
    public static final OfInt unresolved_subtable_count$layout() {
        return unresolved_subtable_count$LAYOUT;
    }

    private static final long unresolved_subtable_count$OFFSET = $LAYOUT.byteOffset(groupElement("unresolved_subtable_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int unresolved_subtable_count
     * }
     */
    public static final long unresolved_subtable_count$offset() {
        return unresolved_subtable_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int unresolved_subtable_count
     * }
     */
    public static int unresolved_subtable_count(MemorySegment struct) {
        return struct.get(unresolved_subtable_count$LAYOUT, unresolved_subtable_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int unresolved_subtable_count
     * }
     */
    public static void unresolved_subtable_count(MemorySegment struct, int fieldValue) {
        struct.set(unresolved_subtable_count$LAYOUT, unresolved_subtable_count$OFFSET, fieldValue);
    }

    private static final SequenceLayout unresolved_subtable_names$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("unresolved_subtable_names"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static final SequenceLayout unresolved_subtable_names$layout() {
        return unresolved_subtable_names$LAYOUT;
    }

    private static final long unresolved_subtable_names$OFFSET = $LAYOUT.byteOffset(groupElement("unresolved_subtable_names"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static final long unresolved_subtable_names$offset() {
        return unresolved_subtable_names$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static MemorySegment unresolved_subtable_names(MemorySegment struct) {
        return struct.asSlice(unresolved_subtable_names$OFFSET, unresolved_subtable_names$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static void unresolved_subtable_names(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, unresolved_subtable_names$OFFSET, unresolved_subtable_names$LAYOUT.byteSize());
    }

    private static long[] unresolved_subtable_names$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static long[] unresolved_subtable_names$dimensions() {
        return unresolved_subtable_names$DIMS;
    }
    private static final VarHandle unresolved_subtable_names$ELEM_HANDLE = unresolved_subtable_names$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static MemorySegment unresolved_subtable_names(MemorySegment struct, long index0) {
        return (MemorySegment)unresolved_subtable_names$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char *unresolved_subtable_names[8]
     * }
     */
    public static void unresolved_subtable_names(MemorySegment struct, long index0, MemorySegment fieldValue) {
        unresolved_subtable_names$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt subtable_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("subtable_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int subtable_count
     * }
     */
    public static final OfInt subtable_count$layout() {
        return subtable_count$LAYOUT;
    }

    private static final long subtable_count$OFFSET = $LAYOUT.byteOffset(groupElement("subtable_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int subtable_count
     * }
     */
    public static final long subtable_count$offset() {
        return subtable_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int subtable_count
     * }
     */
    public static int subtable_count(MemorySegment struct) {
        return struct.get(subtable_count$LAYOUT, subtable_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int subtable_count
     * }
     */
    public static void subtable_count(MemorySegment struct, int fieldValue) {
        struct.set(subtable_count$LAYOUT, subtable_count$OFFSET, fieldValue);
    }

    private static final AddressLayout subtable_pool_offset$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("subtable_pool_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *subtable_pool_offset
     * }
     */
    public static final AddressLayout subtable_pool_offset$layout() {
        return subtable_pool_offset$LAYOUT;
    }

    private static final long subtable_pool_offset$OFFSET = $LAYOUT.byteOffset(groupElement("subtable_pool_offset"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *subtable_pool_offset
     * }
     */
    public static final long subtable_pool_offset$offset() {
        return subtable_pool_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *subtable_pool_offset
     * }
     */
    public static MemorySegment subtable_pool_offset(MemorySegment struct) {
        return struct.get(subtable_pool_offset$LAYOUT, subtable_pool_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *subtable_pool_offset
     * }
     */
    public static void subtable_pool_offset(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(subtable_pool_offset$LAYOUT, subtable_pool_offset$OFFSET, fieldValue);
    }

    private static final AddressLayout subtable_pool_count$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("subtable_pool_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *subtable_pool_count
     * }
     */
    public static final AddressLayout subtable_pool_count$layout() {
        return subtable_pool_count$LAYOUT;
    }

    private static final long subtable_pool_count$OFFSET = $LAYOUT.byteOffset(groupElement("subtable_pool_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *subtable_pool_count
     * }
     */
    public static final long subtable_pool_count$offset() {
        return subtable_pool_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *subtable_pool_count
     * }
     */
    public static MemorySegment subtable_pool_count(MemorySegment struct) {
        return struct.get(subtable_pool_count$LAYOUT, subtable_pool_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *subtable_pool_count
     * }
     */
    public static void subtable_pool_count(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(subtable_pool_count$LAYOUT, subtable_pool_count$OFFSET, fieldValue);
    }

    private static final OfLong prng_state$LAYOUT = (OfLong)$LAYOUT.select(groupElement("prng_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t prng_state
     * }
     */
    public static final OfLong prng_state$layout() {
        return prng_state$LAYOUT;
    }

    private static final long prng_state$OFFSET = $LAYOUT.byteOffset(groupElement("prng_state"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t prng_state
     * }
     */
    public static final long prng_state$offset() {
        return prng_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t prng_state
     * }
     */
    public static long prng_state(MemorySegment struct) {
        return struct.get(prng_state$LAYOUT, prng_state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t prng_state
     * }
     */
    public static void prng_state(MemorySegment struct, long fieldValue) {
        struct.set(prng_state$LAYOUT, prng_state$OFFSET, fieldValue);
    }

    private static final OfInt generated_item_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("generated_item_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int generated_item_count
     * }
     */
    public static final OfInt generated_item_count$layout() {
        return generated_item_count$LAYOUT;
    }

    private static final long generated_item_count$OFFSET = $LAYOUT.byteOffset(groupElement("generated_item_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int generated_item_count
     * }
     */
    public static final long generated_item_count$offset() {
        return generated_item_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int generated_item_count
     * }
     */
    public static int generated_item_count(MemorySegment struct) {
        return struct.get(generated_item_count$LAYOUT, generated_item_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int generated_item_count
     * }
     */
    public static void generated_item_count(MemorySegment struct, int fieldValue) {
        struct.set(generated_item_count$LAYOUT, generated_item_count$OFFSET, fieldValue);
    }

    private static final SequenceLayout generated_items$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("generated_items"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static final SequenceLayout generated_items$layout() {
        return generated_items$LAYOUT;
    }

    private static final long generated_items$OFFSET = $LAYOUT.byteOffset(groupElement("generated_items"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static final long generated_items$offset() {
        return generated_items$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static MemorySegment generated_items(MemorySegment struct) {
        return struct.asSlice(generated_items$OFFSET, generated_items$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static void generated_items(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, generated_items$OFFSET, generated_items$LAYOUT.byteSize());
    }

    private static long[] generated_items$DIMS = { 27 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static long[] generated_items$dimensions() {
        return generated_items$DIMS;
    }
    private static final MethodHandle generated_items$ELEM_HANDLE = generated_items$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static MemorySegment generated_items(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)generated_items$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * ItemStack generated_items[27]
     * }
     */
    public static void generated_items(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, generated_items(struct, index0), 0L, ItemStack.layout().byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

