// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct LootPool {
 *     int min_rolls;
 *     int max_rolls;
 *     RollCountFunction roll_count_function;
 *     int total_weight;
 *     int *precomputed_loot;
 *     int entry_count;
 *     int *entry_to_item;
 *     int *entry_functions_index;
 *     int *entry_functions_count;
 *     LootFunction *loot_functions;
 * }
 * }
 */
public class LootPool {

    LootPool() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("min_rolls"),
        Cubiomes.C_INT.withName("max_rolls"),
        Cubiomes.C_POINTER.withName("roll_count_function"),
        Cubiomes.C_INT.withName("total_weight"),
        MemoryLayout.paddingLayout(4),
        Cubiomes.C_POINTER.withName("precomputed_loot"),
        Cubiomes.C_INT.withName("entry_count"),
        MemoryLayout.paddingLayout(4),
        Cubiomes.C_POINTER.withName("entry_to_item"),
        Cubiomes.C_POINTER.withName("entry_functions_index"),
        Cubiomes.C_POINTER.withName("entry_functions_count"),
        Cubiomes.C_POINTER.withName("loot_functions")
    ).withName("LootPool");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt min_rolls$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min_rolls"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min_rolls
     * }
     */
    public static final OfInt min_rolls$layout() {
        return min_rolls$LAYOUT;
    }

    private static final long min_rolls$OFFSET = $LAYOUT.byteOffset(groupElement("min_rolls"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min_rolls
     * }
     */
    public static final long min_rolls$offset() {
        return min_rolls$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min_rolls
     * }
     */
    public static int min_rolls(MemorySegment struct) {
        return struct.get(min_rolls$LAYOUT, min_rolls$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min_rolls
     * }
     */
    public static void min_rolls(MemorySegment struct, int fieldValue) {
        struct.set(min_rolls$LAYOUT, min_rolls$OFFSET, fieldValue);
    }

    private static final OfInt max_rolls$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max_rolls"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max_rolls
     * }
     */
    public static final OfInt max_rolls$layout() {
        return max_rolls$LAYOUT;
    }

    private static final long max_rolls$OFFSET = $LAYOUT.byteOffset(groupElement("max_rolls"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max_rolls
     * }
     */
    public static final long max_rolls$offset() {
        return max_rolls$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max_rolls
     * }
     */
    public static int max_rolls(MemorySegment struct) {
        return struct.get(max_rolls$LAYOUT, max_rolls$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max_rolls
     * }
     */
    public static void max_rolls(MemorySegment struct, int fieldValue) {
        struct.set(max_rolls$LAYOUT, max_rolls$OFFSET, fieldValue);
    }

    private static final AddressLayout roll_count_function$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("roll_count_function"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RollCountFunction roll_count_function
     * }
     */
    public static final AddressLayout roll_count_function$layout() {
        return roll_count_function$LAYOUT;
    }

    private static final long roll_count_function$OFFSET = $LAYOUT.byteOffset(groupElement("roll_count_function"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RollCountFunction roll_count_function
     * }
     */
    public static final long roll_count_function$offset() {
        return roll_count_function$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RollCountFunction roll_count_function
     * }
     */
    public static MemorySegment roll_count_function(MemorySegment struct) {
        return struct.get(roll_count_function$LAYOUT, roll_count_function$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RollCountFunction roll_count_function
     * }
     */
    public static void roll_count_function(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(roll_count_function$LAYOUT, roll_count_function$OFFSET, fieldValue);
    }

    private static final OfInt total_weight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("total_weight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int total_weight
     * }
     */
    public static final OfInt total_weight$layout() {
        return total_weight$LAYOUT;
    }

    private static final long total_weight$OFFSET = $LAYOUT.byteOffset(groupElement("total_weight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int total_weight
     * }
     */
    public static final long total_weight$offset() {
        return total_weight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int total_weight
     * }
     */
    public static int total_weight(MemorySegment struct) {
        return struct.get(total_weight$LAYOUT, total_weight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int total_weight
     * }
     */
    public static void total_weight(MemorySegment struct, int fieldValue) {
        struct.set(total_weight$LAYOUT, total_weight$OFFSET, fieldValue);
    }

    private static final AddressLayout precomputed_loot$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("precomputed_loot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *precomputed_loot
     * }
     */
    public static final AddressLayout precomputed_loot$layout() {
        return precomputed_loot$LAYOUT;
    }

    private static final long precomputed_loot$OFFSET = $LAYOUT.byteOffset(groupElement("precomputed_loot"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *precomputed_loot
     * }
     */
    public static final long precomputed_loot$offset() {
        return precomputed_loot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *precomputed_loot
     * }
     */
    public static MemorySegment precomputed_loot(MemorySegment struct) {
        return struct.get(precomputed_loot$LAYOUT, precomputed_loot$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *precomputed_loot
     * }
     */
    public static void precomputed_loot(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(precomputed_loot$LAYOUT, precomputed_loot$OFFSET, fieldValue);
    }

    private static final OfInt entry_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("entry_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int entry_count
     * }
     */
    public static final OfInt entry_count$layout() {
        return entry_count$LAYOUT;
    }

    private static final long entry_count$OFFSET = $LAYOUT.byteOffset(groupElement("entry_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int entry_count
     * }
     */
    public static final long entry_count$offset() {
        return entry_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int entry_count
     * }
     */
    public static int entry_count(MemorySegment struct) {
        return struct.get(entry_count$LAYOUT, entry_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int entry_count
     * }
     */
    public static void entry_count(MemorySegment struct, int fieldValue) {
        struct.set(entry_count$LAYOUT, entry_count$OFFSET, fieldValue);
    }

    private static final AddressLayout entry_to_item$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("entry_to_item"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *entry_to_item
     * }
     */
    public static final AddressLayout entry_to_item$layout() {
        return entry_to_item$LAYOUT;
    }

    private static final long entry_to_item$OFFSET = $LAYOUT.byteOffset(groupElement("entry_to_item"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *entry_to_item
     * }
     */
    public static final long entry_to_item$offset() {
        return entry_to_item$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *entry_to_item
     * }
     */
    public static MemorySegment entry_to_item(MemorySegment struct) {
        return struct.get(entry_to_item$LAYOUT, entry_to_item$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *entry_to_item
     * }
     */
    public static void entry_to_item(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(entry_to_item$LAYOUT, entry_to_item$OFFSET, fieldValue);
    }

    private static final AddressLayout entry_functions_index$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("entry_functions_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *entry_functions_index
     * }
     */
    public static final AddressLayout entry_functions_index$layout() {
        return entry_functions_index$LAYOUT;
    }

    private static final long entry_functions_index$OFFSET = $LAYOUT.byteOffset(groupElement("entry_functions_index"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *entry_functions_index
     * }
     */
    public static final long entry_functions_index$offset() {
        return entry_functions_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *entry_functions_index
     * }
     */
    public static MemorySegment entry_functions_index(MemorySegment struct) {
        return struct.get(entry_functions_index$LAYOUT, entry_functions_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *entry_functions_index
     * }
     */
    public static void entry_functions_index(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(entry_functions_index$LAYOUT, entry_functions_index$OFFSET, fieldValue);
    }

    private static final AddressLayout entry_functions_count$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("entry_functions_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *entry_functions_count
     * }
     */
    public static final AddressLayout entry_functions_count$layout() {
        return entry_functions_count$LAYOUT;
    }

    private static final long entry_functions_count$OFFSET = $LAYOUT.byteOffset(groupElement("entry_functions_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *entry_functions_count
     * }
     */
    public static final long entry_functions_count$offset() {
        return entry_functions_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *entry_functions_count
     * }
     */
    public static MemorySegment entry_functions_count(MemorySegment struct) {
        return struct.get(entry_functions_count$LAYOUT, entry_functions_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *entry_functions_count
     * }
     */
    public static void entry_functions_count(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(entry_functions_count$LAYOUT, entry_functions_count$OFFSET, fieldValue);
    }

    private static final AddressLayout loot_functions$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("loot_functions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * LootFunction *loot_functions
     * }
     */
    public static final AddressLayout loot_functions$layout() {
        return loot_functions$LAYOUT;
    }

    private static final long loot_functions$OFFSET = $LAYOUT.byteOffset(groupElement("loot_functions"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * LootFunction *loot_functions
     * }
     */
    public static final long loot_functions$offset() {
        return loot_functions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * LootFunction *loot_functions
     * }
     */
    public static MemorySegment loot_functions(MemorySegment struct) {
        return struct.get(loot_functions$LAYOUT, loot_functions$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * LootFunction *loot_functions
     * }
     */
    public static void loot_functions(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(loot_functions$LAYOUT, loot_functions$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

