// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MobEffect {
 *     const int effect;
 *     const char *effect_name;
 *     const int is_instantaneous;
 * }
 * }
 */
public class MobEffect {

    MobEffect() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("effect"),
        MemoryLayout.paddingLayout(4),
        Cubiomes.C_POINTER.withName("effect_name"),
        Cubiomes.C_INT.withName("is_instantaneous"),
        MemoryLayout.paddingLayout(4)
    ).withName("MobEffect");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt effect$LAYOUT = (OfInt)$LAYOUT.select(groupElement("effect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int effect
     * }
     */
    public static final OfInt effect$layout() {
        return effect$LAYOUT;
    }

    private static final long effect$OFFSET = $LAYOUT.byteOffset(groupElement("effect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int effect
     * }
     */
    public static final long effect$offset() {
        return effect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int effect
     * }
     */
    public static int effect(MemorySegment struct) {
        return struct.get(effect$LAYOUT, effect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int effect
     * }
     */
    public static void effect(MemorySegment struct, int fieldValue) {
        struct.set(effect$LAYOUT, effect$OFFSET, fieldValue);
    }

    private static final AddressLayout effect_name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("effect_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *effect_name
     * }
     */
    public static final AddressLayout effect_name$layout() {
        return effect_name$LAYOUT;
    }

    private static final long effect_name$OFFSET = $LAYOUT.byteOffset(groupElement("effect_name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *effect_name
     * }
     */
    public static final long effect_name$offset() {
        return effect_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *effect_name
     * }
     */
    public static MemorySegment effect_name(MemorySegment struct) {
        return struct.get(effect_name$LAYOUT, effect_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *effect_name
     * }
     */
    public static void effect_name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(effect_name$LAYOUT, effect_name$OFFSET, fieldValue);
    }

    private static final OfInt is_instantaneous$LAYOUT = (OfInt)$LAYOUT.select(groupElement("is_instantaneous"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const int is_instantaneous
     * }
     */
    public static final OfInt is_instantaneous$layout() {
        return is_instantaneous$LAYOUT;
    }

    private static final long is_instantaneous$OFFSET = $LAYOUT.byteOffset(groupElement("is_instantaneous"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const int is_instantaneous
     * }
     */
    public static final long is_instantaneous$offset() {
        return is_instantaneous$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const int is_instantaneous
     * }
     */
    public static int is_instantaneous(MemorySegment struct) {
        return struct.get(is_instantaneous$LAYOUT, is_instantaneous$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const int is_instantaneous
     * }
     */
    public static void is_instantaneous(MemorySegment struct, int fieldValue) {
        struct.set(is_instantaneous$LAYOUT, is_instantaneous$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

