// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct MobEffectEntry {
 *     const MobEffect *mob_effect;
 *     int min;
 *     int max;
 * }
 * }
 */
public class MobEffectEntry {

    MobEffectEntry() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_POINTER.withName("mob_effect"),
        Cubiomes.C_INT.withName("min"),
        Cubiomes.C_INT.withName("max")
    ).withName("MobEffectEntry");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout mob_effect$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("mob_effect"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const MobEffect *mob_effect
     * }
     */
    public static final AddressLayout mob_effect$layout() {
        return mob_effect$LAYOUT;
    }

    private static final long mob_effect$OFFSET = $LAYOUT.byteOffset(groupElement("mob_effect"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const MobEffect *mob_effect
     * }
     */
    public static final long mob_effect$offset() {
        return mob_effect$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const MobEffect *mob_effect
     * }
     */
    public static MemorySegment mob_effect(MemorySegment struct) {
        return struct.get(mob_effect$LAYOUT, mob_effect$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const MobEffect *mob_effect
     * }
     */
    public static void mob_effect(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(mob_effect$LAYOUT, mob_effect$OFFSET, fieldValue);
    }

    private static final OfInt min$LAYOUT = (OfInt)$LAYOUT.select(groupElement("min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int min
     * }
     */
    public static final OfInt min$layout() {
        return min$LAYOUT;
    }

    private static final long min$OFFSET = $LAYOUT.byteOffset(groupElement("min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int min
     * }
     */
    public static final long min$offset() {
        return min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int min
     * }
     */
    public static int min(MemorySegment struct) {
        return struct.get(min$LAYOUT, min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int min
     * }
     */
    public static void min(MemorySegment struct, int fieldValue) {
        struct.set(min$LAYOUT, min$OFFSET, fieldValue);
    }

    private static final OfInt max$LAYOUT = (OfInt)$LAYOUT.select(groupElement("max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int max
     * }
     */
    public static final OfInt max$layout() {
        return max$LAYOUT;
    }

    private static final long max$OFFSET = $LAYOUT.byteOffset(groupElement("max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int max
     * }
     */
    public static final long max$offset() {
        return max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int max
     * }
     */
    public static int max(MemorySegment struct) {
        return struct.get(max$LAYOUT, max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int max
     * }
     */
    public static void max(MemorySegment struct, int fieldValue) {
        struct.set(max$LAYOUT, max$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

