// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OreVeinConfig {
 *     uint32_t oreBlock;
 *     uint32_t rawOreBlock;
 *     uint32_t fillerBlock;
 *     int32_t minY;
 *     int32_t maxY;
 * }
 * }
 */
public class OreVeinConfig {

    OreVeinConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("oreBlock"),
        Cubiomes.C_INT.withName("rawOreBlock"),
        Cubiomes.C_INT.withName("fillerBlock"),
        Cubiomes.C_INT.withName("minY"),
        Cubiomes.C_INT.withName("maxY")
    ).withName("OreVeinConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt oreBlock$LAYOUT = (OfInt)$LAYOUT.select(groupElement("oreBlock"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static final OfInt oreBlock$layout() {
        return oreBlock$LAYOUT;
    }

    private static final long oreBlock$OFFSET = $LAYOUT.byteOffset(groupElement("oreBlock"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static final long oreBlock$offset() {
        return oreBlock$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static int oreBlock(MemorySegment struct) {
        return struct.get(oreBlock$LAYOUT, oreBlock$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t oreBlock
     * }
     */
    public static void oreBlock(MemorySegment struct, int fieldValue) {
        struct.set(oreBlock$LAYOUT, oreBlock$OFFSET, fieldValue);
    }

    private static final OfInt rawOreBlock$LAYOUT = (OfInt)$LAYOUT.select(groupElement("rawOreBlock"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t rawOreBlock
     * }
     */
    public static final OfInt rawOreBlock$layout() {
        return rawOreBlock$LAYOUT;
    }

    private static final long rawOreBlock$OFFSET = $LAYOUT.byteOffset(groupElement("rawOreBlock"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t rawOreBlock
     * }
     */
    public static final long rawOreBlock$offset() {
        return rawOreBlock$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t rawOreBlock
     * }
     */
    public static int rawOreBlock(MemorySegment struct) {
        return struct.get(rawOreBlock$LAYOUT, rawOreBlock$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t rawOreBlock
     * }
     */
    public static void rawOreBlock(MemorySegment struct, int fieldValue) {
        struct.set(rawOreBlock$LAYOUT, rawOreBlock$OFFSET, fieldValue);
    }

    private static final OfInt fillerBlock$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fillerBlock"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t fillerBlock
     * }
     */
    public static final OfInt fillerBlock$layout() {
        return fillerBlock$LAYOUT;
    }

    private static final long fillerBlock$OFFSET = $LAYOUT.byteOffset(groupElement("fillerBlock"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t fillerBlock
     * }
     */
    public static final long fillerBlock$offset() {
        return fillerBlock$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t fillerBlock
     * }
     */
    public static int fillerBlock(MemorySegment struct) {
        return struct.get(fillerBlock$LAYOUT, fillerBlock$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t fillerBlock
     * }
     */
    public static void fillerBlock(MemorySegment struct, int fieldValue) {
        struct.set(fillerBlock$LAYOUT, fillerBlock$OFFSET, fieldValue);
    }

    private static final OfInt minY$LAYOUT = (OfInt)$LAYOUT.select(groupElement("minY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t minY
     * }
     */
    public static final OfInt minY$layout() {
        return minY$LAYOUT;
    }

    private static final long minY$OFFSET = $LAYOUT.byteOffset(groupElement("minY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t minY
     * }
     */
    public static final long minY$offset() {
        return minY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t minY
     * }
     */
    public static int minY(MemorySegment struct) {
        return struct.get(minY$LAYOUT, minY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t minY
     * }
     */
    public static void minY(MemorySegment struct, int fieldValue) {
        struct.set(minY$LAYOUT, minY$OFFSET, fieldValue);
    }

    private static final OfInt maxY$LAYOUT = (OfInt)$LAYOUT.select(groupElement("maxY"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t maxY
     * }
     */
    public static final OfInt maxY$layout() {
        return maxY$LAYOUT;
    }

    private static final long maxY$OFFSET = $LAYOUT.byteOffset(groupElement("maxY"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t maxY
     * }
     */
    public static final long maxY$offset() {
        return maxY$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t maxY
     * }
     */
    public static int maxY(MemorySegment struct) {
        return struct.get(maxY$LAYOUT, maxY$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t maxY
     * }
     */
    public static void maxY(MemorySegment struct, int fieldValue) {
        struct.set(maxY$LAYOUT, maxY$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

