// Generated by jextract

package dev.xpple.cubiomes;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct RandomSource {
 *     int type;
 *     union {
 *         uint64_t jr;
 *         Xoroshiro xr;
 *     };
 * }
 * }
 */
public class RandomSource {

    RandomSource() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Cubiomes.C_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        MemoryLayout.unionLayout(
            Cubiomes.C_LONG.withName("jr"),
            Xoroshiro.layout().withName("xr")
        ).withName("$anon$405:5")
    ).withName("RandomSource");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = $LAYOUT.byteOffset(groupElement("type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final OfLong jr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("$anon$405:5"), groupElement("jr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t jr
     * }
     */
    public static final OfLong jr$layout() {
        return jr$LAYOUT;
    }

    private static final long jr$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$405:5"), groupElement("jr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t jr
     * }
     */
    public static final long jr$offset() {
        return jr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t jr
     * }
     */
    public static long jr(MemorySegment struct) {
        return struct.get(jr$LAYOUT, jr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t jr
     * }
     */
    public static void jr(MemorySegment struct, long fieldValue) {
        struct.set(jr$LAYOUT, jr$OFFSET, fieldValue);
    }

    private static final GroupLayout xr$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("$anon$405:5"), groupElement("xr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Xoroshiro xr
     * }
     */
    public static final GroupLayout xr$layout() {
        return xr$LAYOUT;
    }

    private static final long xr$OFFSET = $LAYOUT.byteOffset(groupElement("$anon$405:5"), groupElement("xr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Xoroshiro xr
     * }
     */
    public static final long xr$offset() {
        return xr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Xoroshiro xr
     * }
     */
    public static MemorySegment xr(MemorySegment struct) {
        return struct.asSlice(xr$OFFSET, xr$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Xoroshiro xr
     * }
     */
    public static void xr(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, xr$OFFSET, xr$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

